### ISSUE TITLE
“Add repos…” is green even once you’ve already added some

### ISSUE THREAD

**Issue by bartaz** [canonical-web-and-design/build.snapcraft.io#1000]
@matthewpaulthomas commented on [Thu Aug 24 2017](https://github.com/CanonicalLtd/snappy-design-squad/issues/106)

1\. Start using BSI with a GitHub account that does not have any organization repos.
2\. When the Add repos dialog first appears, choose “Cancel”.
3\. Choose “Add repos…” and select at least one repo to add.

What you see:
2\. The “Add repos…” button is green.
3\. The “Add repos…” button is still green.

What you should see:
2\. The “Add repos…” button is green.
3\. The “Add repos…” button is now a neutral color. 

Once you have at least one repo, it is much less likely that adding a repo is the next thing you want to do. So the “Add repos…” button should no longer be styled as the default action.

[Thanks to @Greggless in #103 for prompting me to report this.]

**Comment by solazio** [comment]
This is not relevant now as you can link GitHub repos on https://snapcraft.io/ovi-test/builds
