### ISSUE TITLE
“Don’t have snapcraft? Install it…” doesn’t link to simple install instructions 

### ISSUE THREAD

**Issue by nottrobin** [canonical-web-and-design/build.snapcraft.io#1001]
_From @evandandrea on May 5, 2017 13:20_

<img width="1053" alt="screen shot 2017-05-05 at 09 14 16" src="https://cloud.githubusercontent.com/assets/1523179/25746854/48789d1e-3173-11e7-9dd1-68ecd2fc8ee6.png">
<img width="1048" alt="screen shot 2017-05-05 at 09 15 00" src="https://cloud.githubusercontent.com/assets/1523179/25746881/60e50536-3173-11e7-89da-c1e6d37cf7d6.png">

On https://build.snapcraft.io, at the point you are introduced to the snapcraft.yaml format for the first time we provide a link to snapcraft install instructions. Right now this link points at the create page, but this presents a couple of issues:

- This uses the apt package. We should point at the snapcraft snap, as that's cross platform. We should also explain how to get snapd installed.
- This takes you through the tour, which is fine for the case where you arrive on the [create](https://snapcraft.io/create) page from snapcraft.io, but we already link you to [your-first-snap](https://snapcraft.io/docs/build-snaps/your-first-snap) from this part of build.snapcraft.io.

_Copied from original issue: canonical-webteam-archive/snapcraft.io-static-pages#315_

**Comment by solazio** [comment]
Not relevant for snapcraft.io
