### ISSUE TITLE
Hanging while signing into Ubuntu One

### ISSUE THREAD

**Issue by popey** [canonical-web-and-design/build.snapcraft.io#1091]
## Summary

Trying to hook a new repo up to build. I have created a branch new browser profile, and logged into build using my github creds. I also separately in the same session logged into U1/Launchpad, so I know my creds are good.

## Process

Add a repo
Try to register the name (it's already registered under the snapcrafters name)

## Current and expected result

Expect to get sent via SSO, but it just sits there forever.

## Screenshot

![image](https://user-images.githubusercontent.com/1841272/39892180-a7eb38ea-5497-11e8-9d59-3916881d80b7.png)

Sometimes I get to click the Register Name button, sometimes it opens that grey area and is already a spinner on the button.

**Comment by nottrobin** [comment]
build.snapcraft.io is being retired. Please refile this on snapcraft.io if it's still a problem in the new experience.
