### ISSUE TITLE
Errors when deleting repo are not shown

### ISSUE THREAD

**Issue by bartaz** [canonical-web-and-design/build.snapcraft.io#1105]
Found while debugging #1005

If any error happens while removing a repo deleting doesn't succeed (which is fine), but there is no feedback to the user at all.
Only in browser console it can be seen there some API request resulted in an error.

## Process

- have some repo that fails to delete (for example you are not admin of it)
- try to remove it
- nothing happens

## Expected result

While API errors when deleting repo should be quite rare we can't ignore them and should give user some feedback when they happen, so they know that something happen (and if they can try again).

**Comment by solazio** [comment]
This is now fix in the `Builds` tab on snapcraft.io
