### ISSUE TITLE
Using ./run script causes dependency issues

### ISSUE THREAD

**Issue by bartaz** [canonical-web-and-design/build.snapcraft.io#1128]
## Summary

Even that it's not 'officially' documented in readme BSI contains a run script and was meat to potentially be developed using it to build and run BSI inside of the docker container.

But it causes a number of issues around npm dependencies mostly coming from the fact that ./run uses yarn by default and BSI dependencies are based on npm and npm-shrinkwrap.json.
Yarn doesn't seem to be taking npm-shrinkwrap into account, so it installs the latest allowed versions of modules from package.json which leads to inconsistent environment between npm and yarn.

Most notably Vanilla gets updated from 1.6.5 to 1.8, which even that officially was not a breaking change it conceptually is and prevents BSI Vanilla module styles from compiling.

## Expected result

We should either:
- move BSI from npm to yarn completely to be able to use run script by default without issues
- change run script for BSI to use npm instead of yarn
- get rid or run script for now until we can have one that fully works

## Current result

Current implementation or run script for BSI simply doesn't work and can lead to some unnecessary changes being pushed to repo by mistake.

Having run script in project gives a promise it can be used like in any other webteam project, but it this stage it can be very problematic.

**Comment by solazio** [comment]
Not relevant for snapcraft.io, closing
