### ISSUE TITLE
Can't sign out from BSI

### ISSUE THREAD

**Issue by bartaz** [canonical-web-and-design/build.snapcraft.io#1136]
## Summary

There seems to be some issues with signing out from BSI (with redirect to snapcraft.io)

## Process

1. Sign out both from snapcraft.io and BSI (remove cookies to be sure)
2. Go to snapcraft.io, sign in to Developer account
3. Go to 'Build with GitHub' (you will be authenticated to BSI via GH)
4. Click 'Sign out' while in BSI
5. You are redirected back to snapcraft.io and signed out from snapcraft
6. Go 'Back' in the browser (or go to build.snapcraft.io in new tab)
7. You are still signed in to BSI with GH account

## Current and expected result

While QA this I had some cases (maybe different path?) where sign out worked, but usually, when clicking 'Sign out' in BSI it does redirect to snapcraft.io, but doesn't end the session in BSI.

Other way around it seems to work - clicking 'Sign out' in snapcraft.io seems to correctly sign out both from snapcraft and BSI.

It should work in both cases obviously.

**Comment by solazio** [comment]
This is now fixed in snapcraft.io
