### ISSUE TITLE
"To debug this build" instructions does not apply to foreign arch builds

### ISSUE THREAD

**Issue by Lin-Buo-Ren** [canonical-web-and-design/build.snapcraft.io#1143]
## Summary

My snap build *only* fails on armhf arch. and like to debug it, and I notice that the "To debug this build" section doesn't really comply with this situation as it only deals with the same arch. on the host.

I would expect an additional instruction using the `--target-arch` option of the `snapcraft cleanbuild` command.

**Comment by solazio** [comment]
We should add this to snapcraft.io `Build` tab

**Comment by solazio** [comment]
Issue moved to [canonical-web-and-design/snapcraft.io #2846](https://github.com/canonical-web-and-design/snapcraft.io/issues/2846) via [**ZenHub**](https://www.zenhub.com/)
