### ISSUE TITLE
Add repository spins forever

### ISSUE THREAD

**Issue by popey** [canonical-web-and-design/build.snapcraft.io#1155]
## Summary

Trying to add a repo to build, and it's spinning forever after I click 'Add'. This has happened before in issue #1087 

## Process

Go to build.snapcraft.io and login, click add, choose a repo and then hit the add button.

## Current and expected result
The site spins forever, when it should add the repo. 
## Screenshot
![image](https://user-images.githubusercontent.com/1841272/46400989-b3299700-c6f3-11e8-88dc-ce8b343d8493.png)

**Comment by solazio** [comment]
This is fixed on snapcraft.io/build
