### ISSUE TITLE
The snap build status badge's "Copy Markdown code to clipboard"'s icon is visible even when covered by the developer account's drop down menu

### ISSUE THREAD

**Issue by Lin-Buo-Ren** [canonical-web-and-design/build.snapcraft.io#1188]
## Screenshot
![Bug reproducing screenrecord, powered by "Peek"](https://user-images.githubusercontent.com/13408130/50399737-92398500-07bc-11e9-8bb5-38d951b993c9.gif)

## Process
1. Log in developer account at <https://build.snapcraft.io>
1. Go to /user/_user_id_/_snap_id_
1. Click on the Developer Account drop down menu at the right side of the top navigation bar

## Current result
The "Copy Markdown code to clipboard" icon at the right side of the snap build status badge is visible even when the drop down menu covers it

## Expected result
The "Copy Markdown code to clipboard" icon at the right side of the snap build status badge is not visible when the drop down menu covers it

**Comment by solazio** [comment]
With `Build` was moved to snapcraft.io this issue is not relevant anymore. Closing
