### ISSUE TITLE
Repo grayed-out at build.snapcraft.io/select-repositories

### ISSUE THREAD

**Issue by slodki** [canonical-web-and-design/build.snapcraft.io#1191]
### Current behaviour
A repository from GitHub organization with granted permissions is listed but cannot be configured for build process

### Expected behaviour
Repository should be ready to configure after granting permissions by the owner of the GitHub organization.

### Steps to reproduce the problem

1. Created repo owned by organization at GitHub
2. Member of organization team logged at snapcraft.io
3. Snapcraft.io send request to repo owner for authorization of Snappcraft app at Github
4. Request accepted
5. Snapcraft user (GH team member) logged at snapcraft.io can see the repo listed at https://build.snapcraft.io/select-repositories but cannot select it (grayed-out) and configure build process

**Comment by dholbach** [comment]
readthedocs.io allows setting up the webhook manually. Maybe that could be a simple option too.

**Comment by dholbach** [comment]
In our case we use a bot account for the project (so it's not tied to anyone's individual account). It's good practice to give all accounts just the permissions they need.

In this case it might be convenient not having to set up the webhook by hand, but as it's really just one click away, no good reason to give admin privileges. For us this will remain a blocker.

**Comment by dholbach** [comment]
Any more thoughts?

**Comment by matthewpaulthomas** [comment]
I still think that we should just let you add the repo, with daily builds by default. It should be the “On commit” option in the build settings that’s greyed out, not the ability to add the repo in the first place.

**Comment by solazio** [comment]
We consider this fixed in snapcraft.io `Builds` tab
