### ISSUE TITLE
"Debug this build" is outdated

### ISSUE THREAD

**Issue by popey** [canonical-web-and-design/build.snapcraft.io#1194]
## Summary

Have a broken build. Visit the page where it lists your broken build and the details how to rebuild locally. The info is wrong - it refers to `snapcraft cleanbuild` which is not the New Way to do snaps.

![image](https://user-images.githubusercontent.com/1841272/52643778-98eb9b00-2ed5-11e9-8a75-ba994bd0a1b3.png)

**Comment by bartaz** [comment]
@popey @evandandrea What should this box say?
