### ISSUE TITLE
Building manually gives no feedback when problems

### ISSUE THREAD

**Issue by facundobatista** [canonical-web-and-design/build.snapcraft.io#1195]
## Summary

When building manually fails, it gives no error to the user.

This may be related to #996 (but that's closed as fixed, and this issue here is still happening).

## Process

1. Go to a project in build.snapcraft.io that has known autobuild errors (for example [fades](https://build.snapcraft.io/user/PyAr/fades), that fails to build because of [this bug in LP](https://bugs.launchpad.net/launchpad/+bug/1797366))
2. Click on "Build manually now"

## Current and expected result

Currently, it creates a new row in top of "Latest builds" list, that says it's building. It's there some seconds, and then just disappears.

If there's a problem, it should leave at least some error indication, preferably pointing to logs so it can be debugged.

**Comment by solazio** [comment]
This is fixed in the `Builds` tab in snapcraft.io
