### ISSUE TITLE
“No repos” appears briefly when there actually are some

### ISSUE THREAD

**Issue by matthewpaulthomas** [canonical-web-and-design/build.snapcraft.io#1213]
With at least one repo registered for automatic builds:

1\. Go to [snapcraft.io/build](https://snapcraft.io/build).
2\. Click “Set up in minutes” [sic].
3\. Watch closely.

What happens:
- The repos table initially contains the text “No repos”.
- After a second or so, the text is replaced by a spinner.
- The spinner is replaced by the list of repos.

What should happen:
- snapcraft.io should never say “No repos” unless it has discovered that you really do have no repos.

[This is the sequel to #1006.]

**Comment by solazio** [comment]
This is fixed in the `Builds` tab on snapcraft.io
