### ISSUE TITLE
"The snapcraft.yaml can’t be used because it isn’t valid." is a lie

### ISSUE THREAD

**Issue by popey** [canonical-web-and-design/build.snapcraft.io#1214]
## Summary

build.snapcraft.io says the yaml for wire is not valid and as such I cannot trigger a build. This means I cannot publish an updated build of the snap via build.

The yaml is indeed valid, proved by cloning the repo and building it on my PC.

## Process

Visit build.snapcraft.io and sign in
Scroll down list of repos
See wire and note it's not possible to trigger

## Current and expected result

I expect it to allow me to trigger a build. 

## Screenshot

![Screenshot_20190409_151827](https://user-images.githubusercontent.com/1841272/55810766-f79d5180-5adf-11e9-8707-d11bce5343c8.png)

**Comment by bartaz** [comment]
@popey That's online version of validator build.snapcraft uses: http://nodeca.github.io/js-yaml/
It says: 

```
duplicated mapping key at line 18, column 1:
    grade: stable
    ^
```

Seems that local snapcraft just ignores that and builds.

I think we have an issue already reported to show validation errors to help solve such issues quicker.

**Comment by bartaz** [comment]
Seems like underlying issue with yaml file was fixed.

As there is a separate issue to track yaml linting and showing better error messages (#668), I'll close this one as a duplicate.
