### ISSUE TITLE
Errors from backend being unable to reach memcached should not reach users

### ISSUE THREAD

**Issue by sparkiegeek** [canonical-web-and-design/build.snapcraft.io#1221]
## Summary

If the backend cannot reach one of the memcached units, it should just log an error on the backend, but not cause any user visible defects. With multiple units, it should use one of the others, if there are no usable units, then emit a 500.

## Process

* Break one of two memcached units
* Log in to build.snapcraft.io

## Current and expected result

Instead of being visible in the web UI, the non-broken memcached unit should be used. There should be no errors in the web UI.

**Comment by solazio** [comment]
This is not applicable to the new build.snapcraft infrastructure.
