### ISSUE TITLE
No consistent style for links in repo/build tables

### ISSUE THREAD

**Issue by matthewpaulthomas** [canonical-web-and-design/build.snapcraft.io#1226]
There is no consistent style, within and between user, repo, and build pages, for telling which text is a link.

Key: 🔗 link 🚫 not a link

• | User page | Repo page | Build page
-|-|-|-
Repo name / build number | 🔗 black | 🔗 blue | 🚫 black
Build status | 🔗 green/red | 🔗 green/red  | 🚫 green/red
Age | 🔗 green/red | 🚫 green/red | 🚫 green/red

(_Most_ links are underlined on hover, though not all, and not in a consistent colour. But even if that was consistent, you shouldn’t need to scrub a table with a pointing device to figure out which cells are links.)

Depending on how this is fixed, it might fix #763 at the same time.

_Edit: removed guess about someone not finding the build pages._

**Comment by solazio** [comment]
This is fixed in snapcraft.io
