### ISSUE TITLE
The contents of the "Latest build" column in the "Repos to build" table shouldn't be "Never built" during page loading

### ISSUE THREAD

**Issue by Lin-Buo-Ren** [canonical-web-and-design/build.snapcraft.io#1230]
## Process

1. Browse <https://build.snapcraft.io/user/_user_identifier_>
1. Check the contents in the "Latest build" column

## Current and expected result

It should be "Loading..." or "Please wait..."

## Screenshot

![](https://user-images.githubusercontent.com/13408130/61995865-65d24800-b0c0-11e9-8b5c-00d13b62519b.gif)

**Comment by solazio** [comment]
This is fixed in the `Builds` tab on snapcraft.io
