### ISSUE TITLE
Automatic build didn't trigger

### ISSUE THREAD

**Issue by om26er** [canonical-web-and-design/build.snapcraft.io#1236]
## Summary

We have a project that has been set for auto builds for 2 years, I landed a PR for that 30 minutes ago and autobuild hasn't triggered yet. Here is the relevant PR https://github.com/crossbario/crossbar/pull/1649 and the project https://build.snapcraft.io/user/crossbario/crossbar

I have seen that same issue a few days ago with a different project as well.

**Comment by om26er** [comment]
It did eventually...

**Comment by bartaz** [comment]
@om26er Thanks for the update. Yes, it's possible that it make take some time for builds to be triggered if there are some networking issues.

It would even be possible that the webhook call from PR landing would be lost and build will never happen. So it may be the case that sometimes another commit is needed to trigger the build or they can be triggered manually from build.snapcraft.io
