### ISSUE TITLE
Cannot add Github integration: You already registered a claim for the snap name

### ISSUE THREAD

**Issue by thp** [canonical-web-and-design/build.snapcraft.io#1237]
## Summary

I registered (successfully?) the "wavbreaker" snap name. But now I cannot add the Github repo thp/wavbreaker to the build, the website says "You already registered a claim for the snap name".

## Process

1. Go to https://snapcraft.io/build (logged in as user "thp")
2. Click on "Set up in minutes"
3. Click "Add repos..." and select "thp/wavbreaker"
4. Select the name "wavbreaker" to be used

## Current result

Website says: "You already registered a claim for the snap name "wavbreaker"." and does not let me continue

## Expected result

Since I have registered the snap name, I should be allowed to link the Github repo with the snap name.

## Screenshot

<img width="1179" alt="Screenshot 2019-11-22 at 11 37 51" src="https://user-images.githubusercontent.com/135241/69419330-8af85f80-0d1c-11ea-9271-8a5c6b1a949a.png">

**Comment by bartaz** [comment]
Thanks for the report.
If the name was successfully registered you shouldn't get an error like that.

Was the name registered without any issues? Did you need to fill a name claim for (was it registered by someone else before)?

Could you log in to snapcraft.io and check if you see it in registered names list?
https://snapcraft.io/snaps

Or, if you go to the old dashboard, do you see the registered name?
Could you click on it and see if there is anything that may suggest issues with registered name?
https://dashboard.snapcraft.io/stores/snaps/

**Comment by bartaz** [comment]
I just noticed, that the snap seems to be building now:
https://build.snapcraft.io/user/thp/wavbreaker

also on releases page in "Launchpad" tab you can see the builds from build snapcraft:
https://snapcraft.io/wavbreaker/releases

Do you still have the issue with name registration?

**Comment by thp** [comment]
Once I got the e-mail notification that the name claim to "wavbreaker" was accepted, I was able to build it. So possibly the message is misleading and should be something along the lines of "Your request for the name claim is being processed, please check back later."

**Comment by solazio** [comment]
This is not relevant for the new build snapcraft.io infrastructure
