### ISSUE TITLE
Notify webhook returns 500 internal server error randomly

### ISSUE THREAD

**Issue by vilhelmprytz** [canonical-web-and-design/build.snapcraft.io#1238]
## Summary

When I push a new commit, sometimes the webhook that is meant to execute the build job just returns a 500 error.

![github_webhook_BLUR](https://user-images.githubusercontent.com/15460993/71763514-0ed96600-2edd-11ea-97d1-d2938425000d.png)

This screenshot is from my repository webhook settings. As you can see, the requests sometimes fail.

## Process

I'm not sure if it's possible to replicate this issue. It seems to occur randomly.

## Current and expected result

Expected webhook to trigger builds.

**Comment by Lukewh** [comment]
@VilhelmPrytz thanks for the report. We're starting migration of build.snapcraft.io into snapcraft.io, hopefully this should resolve some issues, and we'll ensure to check webhooks. In the meantime, if you come across this error more, or discover any details that seem relevant, please update this issue.

**Comment by VilhelmPrytz** [comment]
Hmm, it seems like it's more prone to return the 500 and not trigger the build if there is a build waiting to be built on Snapcraft (with the status "building soon"). Sometimes the "arm64" and "armhf" architecture takes a really long time before they start to build, so sometimes I push several commits before it even has started.

I see the "Build manually now" is greyed out when a build is still pending. See image.

![build.snapcraft.io](https://user-images.githubusercontent.com/15460993/72174047-20d57000-33d9-11ea-9e2e-670193730a58.png)

**Comment by VilhelmPrytz** [comment]
Again, this is even more frustrating when there is no way to cancel a build. Yesterday, I had to wait 7 hours before the `ppc64el` build started.

**Comment by solazio** [comment]
@vilhelmprytz the reason you have to wait is because there is a queue system on launchpad, and sometimes the waiting time is quite long. Now you should be able to see the estimate queue time if you hover over `Building Soon` status in the builds table.

We believe this is is now fixed in the `Builds` on snapcraft.io, therefore closing.
