### ISSUE TITLE
Builds no longer being triggered by git commits

### ISSUE THREAD

**Issue by popey** [canonical-web-and-design/build.snapcraft.io#1244]
## Summary

On a number of occasions I've modified repos which have been hooked up to build.snapcraft.io for a while, but no builds are triggered. Someone else mentioned this to me but didn't appreciate it was potentially system wide.

## Process

Modify a repo which is connected to build.snapcraft.io. 

## Current and expected result

I modified https://github.com/snapcrafters/opentoonz/ 7 hours ago

I expected a build to appear at https://build.snapcraft.io/user/snapcrafters/opentoonz

Nothing was triggered, I had to manually do so.

## Screenshot

![Screenshot from 2020-02-01 23-13-56](https://user-images.githubusercontent.com/1841272/73600492-a1a30a00-4548-11ea-99da-f9c29bdd47af.png)

**Comment by popey** [comment]
Further, there was a system crash at the datacentre last night, which has left one of my snaps in a wedeged state. I cannot trigger a build (as detailed above) and can't manually trigger a build. So this blocks my ability to build this snap.

**Comment by Lukewh** [comment]
I've been told this should be sorted now? Could you confirm if that's the case please?

**Comment by popey** [comment]
I think it probably is, some of my other snaps have indeed been building based on changes, thanks.
