### ISSUE TITLE
Clarify status of this repo vs canonical-web-and-design/snapcraft.io ?

### ISSUE THREAD

**Issue by anonymouse64** [canonical-web-and-design/build.snapcraft.io#1246]
## Summary

Is this repo still used for build.snapcraft.io (which now redirects to snapcraft.io/build)?

**Comment by Lukewh** [comment]
The Logged in part of build.snapcraft.io is a completely different service hosted separately from snapcraft.io - this is the code for the logged-in part of build.snapcraft.io.
