### ISSUE TITLE
Should not build i386 snaps with base: core20

### ISSUE THREAD

**Issue by anonymouse64** [canonical-web-and-design/build.snapcraft.io#1247]
## Summary

With the release of Ubuntu 20.04, snaps that specify `base: core20` should not auto-trigger builds on the i386 architecture because that will not be possible since there is not an Ubuntu 20.04 for i386, and thus there is not a core20 base snap for i386. 

## Process

Create a snapcraft.yaml with `base: core20` such as this one: https://github.com/anonymouse64/ubuntu-core-initramfs-snap

## Current and expected result

I expected build.snapcraft.io to not try to build for i386 automatically when specifying a snap with `base: core20` in the snapcraft.yaml of a GitHub issue.

Instead it triggered a i386 build, which failed on LP like this:

```
linux32: failed to execute snap: No such file or directory
Install failed
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/lpbuildd/target/build_snap.py", line 259, in run
    self.install()
  File "/usr/lib/python2.7/dist-packages/lpbuildd/target/build_snap.py", line 163, in install
    snap_name])
  File "/usr/lib/python2.7/dist-packages/lpbuildd/target/lxd.py", line 536, in run
    subprocess.check_call(cmd, **kwargs)
  File "/usr/lib/python2.7/subprocess.py", line 541, in check_call
    raise CalledProcessError(retcode, cmd)
CalledProcessError: Command '['lxc', 'exec', 'lp-focal-i386', '--', 'linux32', 'snap', 'install', '--channel=stable', 'core20']' returned non-zero exit status 127
```

See also https://bugs.launchpad.net/launchpad/+bug/1862258 for LP side

**Comment by Lukewh** [comment]
Thanks for the report, we'll look into it.

**Comment by solazio** [comment]
@anonymouse64 I was not able to replicate this. Closing
