### ISSUE TITLE
google analytics 404 in build

### ISSUE THREAD

**Issue by popey** [canonical-web-and-design/build.snapcraft.io#1255]
## Summary
Visit build.snapcraft.io and view your repositories.
Open developer console
Note a 404 from "Failed to load resource: the server responded with a status of 404 ()"
![Screenshot from 2020-03-24 09-14-24](https://user-images.githubusercontent.com/1841272/77408615-e5c7c380-6daf-11ea-8fb9-3d1ce94163a3.png)
The url is https://www.google-analytics.com/gtm/js?id=GTM-MJJ7C2K&cid=1763528910.1584449942

**Comment by Lukewh** [comment]
Hello @popey, are you still seeing this issue? Looks like this was around the time we had issues across all sites and should now be resolved. Cheers

**Comment by nottrobin** [comment]
I don't think this is relevant now, as I can't find a way to end up on build.snapcraft.io when trying to view builds.
