### ISSUE TITLE
Design Charmhub homepage wireframes using new content

### ISSUE THREAD

**Issue by danielmutis** [canonical-web-and-design/build.snapcraft.io#1259]
Content [here](https://docs.google.com/document/d/194S-ZXaWOjB2wgkmZSET1anhzXBvO7AwFoy2yH-Z2HI/edit).

**Comment by danielmutis** [comment]
Wireframe [here](https://zpl.io/V0BLMWw).

**Comment by clagom** [comment]
Thanks @danielmutis, content might change as the copy docs are still WIP. Apart from that I think this is a good start. @spencerbygraves visually I think we can reuse some images / illustrations from the previous CharmHub home page we worked on, and probably some placeholders from the current jaas.ai.

**Comment by Lukewh** [comment]
Blocked waiting on copy doc updates
