### ISSUE TITLE
Mock up About page

### ISSUE THREAD

**Issue by danielmutis** [canonical-web-and-design/build.snapcraft.io#1261]
Content to mock up page [here](https://docs.google.com/document/d/1UuNVajNHcWcF9d-fSnPFl8Zi4sDl21G5K-F09F8c3i8/edit#).

**Comment by danielmutis** [comment]
Wireframe [here](https://zpl.io/a807D7g).

**Comment by Lukewh** [comment]
Blocked waiting on updated copy docs
