### ISSUE TITLE
Error when importing .png image

### ISSUE THREAD

**Issue by bartaz** [canonical-web-and-design/build.snapcraft.io#151]
We currently only support .svg images in webpack config.
But even when I added .png support into loaders-config.js server failed load .png file:

```
/Users/bartaz/Canonical/build.snapcraft.io/node_modules/babel-core/lib/transformation/file/index.js:600
      throw err;
      ^

SyntaxError: /Users/bartaz/Canonical/build.snapcraft.io/src/common/images/gentoo.png: Unexpected character '�' (1:0)
> 1 | �PNG
    | ^
  2 | 
```

Didn't have time to investigate further (found svg logo instead), but if we ever need to support loading png images in webpack we would need to fix that.

**Comment by bartaz** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Error importing .png file](https://trello.com/c/ipOU5kvd/249-error-importing-png-file)

**Comment by solazio** [comment]
Not relevant for snapcraft.io, closing
