### ISSUE TITLE
testimonial component needs to be encapsulated better

### ISSUE THREAD

**Issue by pmahnke** [canonical-web-and-design/build.snapcraft.io#211]
## PROBLEMS

1. the current component cannot place the quote at the bottom of a row of comments without a 'position: relative' on the style .rowItemOneThird - I think this needs to be accomplished with flex instead.
2. the current component requires a logo, but the design does not, if I knew JS better, I assume you could do a simple check

```
if logo
    img src=logo
```

## NOTE

[design spec](https://www.dropbox.com/s/6je201c3jp2as2z/1%20-%20testimonials%20-%20no%20avatar.jpg?dl=0)

**Comment by solazio** [comment]
This is not relevant for snapcraft.io, closing
