### ISSUE TITLE
Can't sign in to U1 with Safari 10

### ISSUE THREAD

**Issue by earnubs** [canonical-web-and-design/build.snapcraft.io#222]
Safari 10 is failing on the OPTIONS request to SCA /dev/api/acl/ with a 403:

```
{"error_list": [{"message": "Authorization Required", "code": "macaroon-permission-required"}]}
```

**Comment by cjwatson** [comment]
Do you have a way to get hold of the request and response headers?

**Comment by earnubs** [comment]
From Safari console:

```
[Error] Failed to load resource: the server responded with a status of 403 (Forbidden) (acl, line 0)
[Error] Failed to load resource: Preflight response is not successful (acl, line 0)
[Error] XMLHttpRequest cannot load https://myapps.developer.ubuntu.com/dev/api/acl/. Preflight response is not successful
```

**Comment by earnubs** [comment]
<img width="415" alt="response" src="https://cloud.githubusercontent.com/assets/167440/23518713/4b18f30e-ff6c-11e6-8e3c-4e4686972612.png">

**Comment by earnubs** [comment]
<img width="426" alt="response" src="https://cloud.githubusercontent.com/assets/167440/23518746/691c491e-ff6c-11e6-9e2a-dac4456e37fe.png">

**Comment by cjwatson** [comment]
https://code.launchpad.net/~cjwatson/software-center-agent/cors-safari-compat/+merge/318826

**Comment by earnubs** [comment]
Test case: https://jsfiddle.net/earnubs/dkauw30q/

**Comment by solazio** [comment]
This was fixed, closing
