### ISSUE TITLE
Spacing between user details, progress bar, first-time text, and main component

### ISSUE THREAD

**Issue by evandandrea** [canonical-web-and-design/build.snapcraft.io#223]
<img width="1044" alt="screen shot 2017-02-24 at 08 58 23" src="https://cloud.githubusercontent.com/assets/1523179/23297014/9eb02c32-fa6f-11e6-9523-f490e44e33a8.png">

The progress bar and first-time text look too closely packed, but I'm not sure what the proper spacing should be. Can someone from design provide guidance?

**Comment by bartaz** [comment]
@jamiedawsonyoung can you have a look at this?

**Comment by jamiedawsonyoung** [comment]
Not able to see what we're using (on my mobile) @bartaz could you let me know what we're using and I'll see what we need to adjust. Ta!

**Comment by jamiedawsonyoung** [comment]
Added a card to Trello for this and linked to this issue.

**Comment by matthewpaulthomas** [comment]
In Trello (which we’re no longer using), Jamie wrote:
> - To solve the space between the user details and first time text I've asked for a light grey strip in the background to hold this info together. This is already issue on the dashboard visual bugs
> - The space underneath the progress bar should be 2rem.

And I wrote:
> Following the principle that things more closely related should be closer together, we should have:
>
> space between progress steps <
> space between progress meter and first-time text <
> space between first-time meter+text and “Choose repos” border <
> space between first-time meter+text and user details.
>
> Dividers/strips may also be necessary, but adding any space that the dividers/strips themselves require will result in the same overall spacing hierarchy anyway.

**Comment by kwm14** [comment]
Hi @matthewpaulthomas did we agree last Friday in our meeting to remove favicon and name? Or shall I update the design based on Jamie's feedback you added?

**Comment by matthewpaulthomas** [comment]
@kwm14 Yes, please remove the large icon+name+ID. The reasons are first that it will be redundant with the icon+ID in the header, and second that we need the vertical space for the “Add repos” dialog to fit on screen below the first-time diagram+text.

**Comment by kwm14** [comment]
## Updated iteration

- this resolves @evandandrea feedback of content being closely packed
- updated design based on @matthewpaulthomas feedback

### Choose a repo
![01-add-repos-none-selected-update](https://cloud.githubusercontent.com/assets/17748020/25708150/8fde9d02-30dd-11e7-88cc-7ee72ed386da.png)

**Comment by matthewpaulthomas** [comment]
@kwm14 Thanks. That does increase the spacing between the “Let’s get started!” text and other elements. However, it still isn’t clear which bits are related — for example, the “Let’s get started!” text is nearer to the dialog below when it’s more related to the diagram above.

Here’s an updated version of the visual hierarchy [I described above](#issuecomment-284394018):

![front page mockup annotated](https://cloud.githubusercontent.com/assets/19801137/25746379/11766f12-319b-11e7-81f7-7de165f8dcdf.png)

The single change that would fix most of these is to make the first-time meter just wide enough for the steps (as it is on [most other sites with a similar pattern](https://baymard.com/checkout-usability/benchmark/step-type/delivery-options)), rather than spanning the full width of the page. That would satisfy A > B, D ≥ B, and C ≥ B.

**Comment by kwm14** [comment]
## Updated iteration

- taking @matthewpaulthomas feedback into consideration
- first-time meter width reduced (looks so much better)

As content needs to be more closely related I explored a couple of versions:

- 002 [progress meter and first-time text] contained in a strip
- 003 [progress meter] and [first time text] positioned in one row split using 6cols each

### 002 Choose a repo
![updates-01-add-repos-none-selected-v3](https://cloud.githubusercontent.com/assets/17748020/25751649/ab96aae6-31ad-11e7-9007-2074e66ea0e4.png)

### 003 Choose a repo
![updates-01-add-repos-none-v2](https://cloud.githubusercontent.com/assets/17748020/25751658/b45aa056-31ad-11e7-856a-d9470d97f0ea.png)

**Comment by matthewpaulthomas** [comment]
@kwm14 Version 002 looks much better, thank you! The dialog spacing will need a little more work once it’s floating over the rest of the page (#564). But for now, I think this mockup solves the issues reported here.

**Comment by solazio** [comment]
This was fixed on snapcraft.io, closing
