### ISSUE TITLE
Spacing between paragraphs and text colouring

### ISSUE THREAD

**Issue by evandandrea** [canonical-web-and-design/build.snapcraft.io#226]
<img width="1046" alt="screen shot 2017-02-24 at 09 14 11" src="https://cloud.githubusercontent.com/assets/1523179/23298003/ba2c6bc0-fa73-11e6-9d4a-264c2d57b847.png">

I think there should be slightly more spacing between "This repo needs a snapcraft.yaml …", "Learn the basics …", and "Don't have snapcraft …". The latter two should be grey, per the spec.

**Comment by evandandrea** [comment]
@jamiedawsonyoung

**Comment by jamiedawsonyoung** [comment]
I've made a card for Trello and linked to this issue. I'll add the solution there so the team can track it and fix it :-)

**Comment by matthewpaulthomas** [comment]
In Trello (which we’re no longer using), Jamie wrote:
> I think the issue is mostly about defining the hierarchy between the message "This repo needs a…" and the helper text "Learn the basics…" and "Don’t have snapcraft…"
>
> It's possible to create this definition if we:
>
> - Increase the message weight to 400
> - Change the helper text to #666 (We can't change the link styles so this colour change is not a hugely noticeable change)
> - Add a 10px margin-bottom to the message (taken from Maas styles)

**Comment by solazio** [comment]
This was fixed on snapcraft.io, closing
