### ISSUE TITLE
Requesting data that we already have in client

### ISSUE THREAD

**Issue by nottrobin** [canonical-web-and-design/build.snapcraft.io#270]
In most cases when we load a view we fetch all the data it needs even if we already have it.

Sometimes it's necessary (if we want to make sure we show up to date info), but it other cases we could show data we already have and not send unnecessary requests and show loading spinners if data is already in the store.

Example: /dashboard (fetching enabled repos and builds), /select-repositories (fetching user repos list)

---

Copied from Trello card: https://trello.com/c/dWSC4Ygr/248-requesting-data-that-we-already-have-in-client
Labels:

**Comment by katiefenn** [comment]
Specifically, make sure build data is not loaded unnecessarily:

"Currently when opening build details page we fetch snap details and builds list (latest 20) even if data about given build is already in the store (from listing).

We shouldn't ask for data that we already have.

Also, it may be possible that given build is not in latest 20, so we should probably try to load data of this particular build, not expecting listing to contain the data."

**Comment by katiefenn** [comment]
K: 3,
B: 3,
C: 3,
R: 4

**Comment by solazio** [comment]
Not relevant for snapcraft.io, closing
