### ISSUE TITLE
Exceptions thrown in components swallowed by promises in Redux

### ISSUE THREAD

**Issue by nottrobin** [canonical-web-and-design/build.snapcraft.io#273]
---

Copied from Trello card: https://trello.com/c/EWazc2Bw/278-exceptions-thrown-in-components-swallowed-by-promises-in-redux
Labels:

**Comment by katiefenn** [comment]
K: 4,
B: 3,
C: 3

**Comment by solazio** [comment]
Not relevant for snapcraft.io, closing
