### ISSUE TITLE
Remove environments/staging.env and environments/production.env

### ISSUE THREAD

**Issue by nottrobin** [canonical-web-and-design/build.snapcraft.io#276]
---

Copied from Trello card: https://trello.com/c/qh6amLDS/282-remove-environments-staging-env-and-environments-production-env
Labels:

**Comment by katiefenn** [comment]
K: 4,
B: 3,
C: 3,
R: 3

**Comment by solazio** [comment]
Not relevant for snapcraft.io, closing
