### ISSUE TITLE
Help developers get up and running with API connectivity

### ISSUE THREAD

**Issue by nottrobin** [canonical-web-and-design/build.snapcraft.io#277]
---

Copied from Trello card: https://trello.com/c/egDZmE6Q/283-service-mocks-coverage
Labels:

**Comment by nottrobin** [comment]
As discussed in the technical debt discussion - rather than continuing to use (and have to maintain) mocks of the APIs, we should make an effort to help the developers get up and running using the real APIs (GitHub, SSO etc.).

This might include writing helper scripts or writing good summary documentation.

**Comment by katiefenn** [comment]
Help wanted: needs prioritization

**Comment by cjwatson** [comment]
C: 3

**Comment by bartaz** [comment]
B: 3

**Comment by solazio** [comment]
Not relevant for snapcraft.io, closing
