### ISSUE TITLE
Acceptance / e2e tests [5]

### ISSUE THREAD

**Issue by nottrobin** [canonical-web-and-design/build.snapcraft.io#278]
Selenium / webdriver tests running via browserstack covering the happy path, same as in my.ubuntu.com

---

Copied from Trello card: https://trello.com/c/FJa0eZvP/284-acceptance-e2e-tests
Labels:

**Comment by katiefenn** [comment]
R: 5,
K: 4,
B: 5,
C: 4

**Comment by matthewpaulthomas** [comment]
[The test plan](https://docs.google.com/spreadsheets/d/1bYIfgKSm0q4zUrlSYGuaaa7LEePnXfaz7QMKjiBdo3M/edit) (Canonical-only link, sorry) that the QA team was working on, including details of test user accounts.

**Comment by solazio** [comment]
Not relevant for snapcraft.io, closing
