### ISSUE TITLE
Split JS bundle file into separate "homepage" and "rest" bundles

### ISSUE THREAD

**Issue by nottrobin** [canonical-web-and-design/build.snapcraft.io#281]
Split out the vendor bundle from the app bundle, check and reduce bundle size were possible.

---

Copied from Trello card: https://trello.com/c/LYJvPrOe/9-webpack-chunking-and-perf-of-bundle-load
Labels:

**Comment by katiefenn** [comment]
K: 2,
R: 3,
C: 3,
B: 3

**Comment by nottrobin** [comment]
We could start by creating a chunk just for the homepage, which doesn't need most of the JavaScript for the rest of the app. But we could lazy-load the rest of the resources in the background after the homepage has loaded.

**Comment by katiefenn** [comment]
Also investigate:

- Pre-loading "rest" bundle on landing page after page has loaded
- Other opportunities for chunking

**Comment by earnubs** [comment]
See also: https://github.com/earnubs/react-hot-loader-starter-kit/blob/master/webpack/config.js#L9

You can create a vendor bundle, but you can also take the vendor scripts out of webpack pipeline altogether and load them as individual scripts from a vendor folder, improving build time and optimising load times with long term caching, http2, etc.

**Comment by bartaz** [comment]
See also #797

**Comment by solazio** [comment]
Not relevant for snapcraft.io, closing
