### ISSUE TITLE
Properly fetch build details from LP

### ISSUE THREAD

**Issue by nottrobin** [canonical-web-and-design/build.snapcraft.io#283]
Currently on builds details page /:owner/:name/builds/:id we don't fetch data of given build from API but we fetch list of the builds (latest 20 builds).

While it works fine for latest builds when list of builds grows longer (and once we add paging for builds list too) user may have a URL for a build that is not in the 20 latest.

So we should properly fetch the data for given build and not rely on its presence in the listing of latest builds.

---

Copied from Trello card: https://trello.com/c/wU2hfSdM/69-properly-fetch-build-details-from-lp
Labels:

**Comment by katiefenn** [comment]
R: 4,
K: 5,
C: 4
B: 4

**Comment by solazio** [comment]
Not relevant for snapcraft.io, closing
