### ISSUE TITLE
Refactoring: share response objects between handlers

### ISSUE THREAD

**Issue by nottrobin** [canonical-web-and-design/build.snapcraft.io#284]
Currently each server side handler (github, launchpad, webhook, etc) define their own possible response object (RESPONSE_NOT_LOGGED_IN, etc), but some of them should be shared between different calls for consistency.

It would be good to have one source of all possible responses from internal API (separate responses.js module?) and indivisual handlers could import responses from it.

It will help reusing similar responses, remove duplication and have more consistency between different API calls.

---

Copied from Trello card: https://trello.com/c/30Aa1VgW/62-refactoring-share-response-objects-between-handlers
Labels:

**Comment by katiefenn** [comment]
Deferred for further discussion

**Comment by solazio** [comment]
No relevant for snapcraft.io, closing
