### ISSUE TITLE
use mapDispatchToProps

### ISSUE THREAD

**Issue by nottrobin** [canonical-web-and-design/build.snapcraft.io#285]
eg. https://github.com/reactjs/react-redux/blob/master/docs/api.md#inject-todos-todoactioncreators-as-todoactions-and-counteractioncreators-as-counteractions

I think it would neaten the code up a little

---

Copied from Trello card: https://trello.com/c/T6xtF4JD/316-use-mapdispatchtoprops
Labels:

**Comment by katiefenn** [comment]
K: 1,
C: 1,
R: 2,
B: 2

**Comment by solazio** [comment]
Not relevant for snapcraft.io, closing
