### ISSUE TITLE
Actions tests use wrong initialState

### ISSUE THREAD

**Issue by nottrobin** [canonical-web-and-design/build.snapcraft.io#286]
In actions state we init mock store with initial state of single reducer (related to actions), but we should really nest the initial state in reducer namespace.

Or if the test really doesn't need initial state just remove it, which would be true for most cases.

More context: https://github.com/canonical-ols/build.snapcraft.io/pull/252/files#r103871452

---

Copied from Trello card: https://trello.com/c/nnpyx939/320-actions-tests-use-wrong-initialstate
Labels:

**Comment by katiefenn** [comment]
B: 2,
K: 2,
C: 2,
R: 1

**Comment by solazio** [comment]
Not relevant for snapcraft.io, closing
