### ISSUE TITLE
Get SCA to track snap name registrations and snap publications to edge from BSI vs. elsewhere

### ISSUE THREAD

**Issue by nottrobin** [canonical-web-and-design/build.snapcraft.io#289]
This will help us track how this site is growing the ecosystem.

---

Copied from Trello card: https://trello.com/c/YKrqDmuB/318-get-sca-to-track-snap-name-registrations-and-snap-publications-to-edge-from-bsi-vs-elsewhere
Labels: MWC priority

**Comment by cjwatson** [comment]
https://code.launchpad.net/~cjwatson/software-center-agent/upload-origin-bsi/+merge/319719 is part of this, although not all of it.

**Comment by magdalena-mirowicz** [comment]
possibly for Public launch

**Comment by solazio** [comment]
No relevant for snapcraft.io, closing
