### ISSUE TITLE
No build log information while build is in progress

### ISSUE THREAD

**Issue by nottrobin** [canonical-web-and-design/build.snapcraft.io#295]
Launchpad doesn't currently have the full build log until the build completes.  It does have the "logtail".  However, this isn't exposed by the API ...

---

Copied from Trello card: https://trello.com/c/EiRF1N7l/314-no-build-log-information-while-build-is-in-progress
Labels:

**Comment by solazio** [comment]
This is fixed in the new `Builds` tab on snapcraft.io
