### ISSUE TITLE
[name not matching] snapcraft.yaml name is invalid

### ISSUE THREAD

**Issue by nottrobin** [canonical-web-and-design/build.snapcraft.io#298]
---

Copied from Trello card: https://trello.com/c/wdLnovA9/326-name-not-matching-snapcraft-yaml-name-is-invalid
Labels:

**Comment by bartaz** [comment]
UI for that requires #297 (knowing the location of snapcraft.yaml in repo)

**Comment by magdalena-mirowicz** [comment]
@matthewpaulthomas please have a look if it should be in beta

**Comment by solazio** [comment]
This is fixed now
