### ISSUE TITLE
[name not matching] snapcraft.yaml name is registered in another repo

### ISSUE THREAD

**Issue by nottrobin** [canonical-web-and-design/build.snapcraft.io#299]
---

Copied from Trello card: https://trello.com/c/vz80RtaB/327-name-not-matching-snapcraft-yaml-name-is-registered-in-another-repo
Labels:

**Comment by pmahnke** [comment]
another repo, but same user has already registered it...

**Comment by bartaz** [comment]
UI for that requires #297 (knowing the location of snapcraft.yaml in repo)

**Comment by magdalena-mirowicz** [comment]
@matthewpaulthomas please have a look if it should be in beta

**Comment by bartaz** [comment]
@matthewpaulthomas The spec defines the text we should show if the name from snapcraft.yaml in one repo is registered in another repo of the same user.
This assumes they have this repo already added in BSI (and registered the name).

There can be another case, where given user has this name registered in the store, but it's not (yet) used by any repo listed in BSI. For example they could have registered this name in store UI or by command line snapcraft.

Should we have another text (possible actions) in such case?

**Comment by matthewpaulthomas** [comment]
@bartaz Good question, but I don’t think we need special text for that case. The generic suggestion, “You can: … Register the name ‘{name in snapcraft.yaml}’”, will be on point.

**Comment by solazio** [comment]
This is fixed in the `Builds` tab on snapcraft.io
