### ISSUE TITLE
[dashboard] Maybe SSO explanation and name registration can be combined

### ISSUE THREAD

**Issue by nottrobin** [canonical-web-and-design/build.snapcraft.io#308]
Would require accepting terms even if you already have. Maybe: 

*“To publish a snap to the store, you need to sign in to Ubuntu One and choose a unique name.”*

---

Copied from Trello card: https://trello.com/c/oyUGDJ6i/261-dashboard-maybe-sso-explanation-and-name-registration-can-be-combined
Labels: design

**Comment by matthewpaulthomas** [comment]
First I’d like to know whether this is technically feasible.

When you click “Sign in and register name”, build.snapcraft.io would need to:
1. Check that the name is valid and not currently registered.
1. Record that GitHub user X is trying to register name Y for repo Z, and block anyone else from doing the same.
1. Send you off to sign in or register to SSO.
1. When you come back, expand the same table cell, and _then_ try to register the name.
1. If you don’t come back, release the name after N minutes.

**Comment by bartaz** [comment]
> 1. Check that the name is valid and not currently registered.

This is quite feasible - we can validate the name already and there is a public store API that allows us to check if name is already registered by someone.

> 2. Record that GitHub user X is trying to register name Y for repo Z, and temporarily block anyone else from registering the same name.

In theory we can store this info in database on BSI side, so this may be used to block other users from registering the same name **through BSI**. We can't block other users from registering this name directly in the store. So other user may still be able to register same name through the store UI - we cannot change that without significant changes on the store part, as there is no way to temporarily 'reserve' the name in the store.

> 3. Send you off to sign in or register to SSO.
> 4. When you come back, expand the same table cell, and then try to register the name.

When user comes back (visits "My repos" page again) we may call BSI server to check if they have any 'in progress' name registrations to complete in database and register these names in such case.

> 5. If you don’t come back, release the name after N minutes.

And periodically server would need to check if any of pending registrations have timed-out - and remove them from database.

So the biggest issue I see is the problem of other user registering the same name directly in the store in the mean time. Of course the worst that would happen in such case is that when first user completes SSO and registration they will get an error that name is already registered.

Also the part of storing 'in progress' registrations for blocking in database and clearing it after some time is a bigger change on BSI part.

**Comment by solazio** [comment]
No relevant for snapcraft.io, closing
