### ISSUE TITLE
[landing page] Workflow diagram doesn’t make it obvious how we save you time/effort

### ISSUE THREAD

**Issue by nottrobin** [canonical-web-and-design/build.snapcraft.io#316]
Can we add something to the steps after you build a snap and before you publish it to show that build.snapcraft.io does these things automatically (where you would have done them manually in the past?)

---

Copied from Trello card: https://trello.com/c/wRoz69Jl/274-landing-page-workflow-diagram-doesn-t-make-it-obvious-how-we-save-you-time-effort
Labels: design

**Comment by jamiedawsonyoung** [comment]
Tackling this in #361

**Comment by nottrobin** [comment]
@jamiedawsonyoung should this be closed?

**Comment by jamiedawsonyoung** [comment]
@nottrobin Maybe but I'd like to keep them open until we've had a first review with Marcus and Teresa so I make sure I don't miss any nuance in the individual issues. Will close them as soon as possible.

**Comment by nottrobin** [comment]
@jamiedawsonyoung Cool. Yep feel free to leave them open as long as they are helpful.

**Comment by jamiedawsonyoung** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [#316 Workflow diagram doesn’t make it obvious how we save you time/effort](https://trello.com/c/ua9HjC9o/599-316-workflow-diagram-doesn-t-make-it-obvious-how-we-save-you-time-effort)

**Comment by carlaberkers** [comment]
this is part of #361

**Comment by matthewpaulthomas** [comment]
No longer treating as part of #361.

**Comment by solazio** [comment]
Not relevant for snapcraft.io, closing
