### ISSUE TITLE
[header] Three adjacent header elements look the same, behave differently [1]

### ISSUE THREAD

**Issue by nottrobin** [canonical-web-and-design/build.snapcraft.io#318]
Currently the header contains:

- “Hi, {name}”, static text
- “Dashboard”, a link
- “Sign out”, a button

These three items are styled exactly the same but behave differently.

Possible partial solutions:

- Replace “Hi, ” with your GitHub profile picture
- Remove “Dashboard” from the header altogether
- Style “Sign out” like a button

---

Copied from Trello card: https://trello.com/c/4tFtWj7S/253-header-three-adjacent-header-elements-look-the-same-behave-differently
Labels: design

**Comment by matthewpaulthomas** [comment]
> Replace “Hi, ” with your GitHub profile picture

Now reported as #426.

> Remove “Dashboard” from the header altogether

This part can be done once #310 (consistent hierarchy navigation) is implemented.

**Comment by jamiedawsonyoung** [comment]
## Design proposal
- Replaced "Hi" with GitHub avatar
- Removed the dashboard link

#### Signed out
![header-signed-out](https://cloud.githubusercontent.com/assets/6909617/23711168/fdacbce0-0416-11e7-947a-288d8279662f.png)

#### Signed in
![header-signed-in](https://cloud.githubusercontent.com/assets/6909617/23711227/2af4d5f2-0417-11e7-943b-c617e4f9d75d.png)

**Comment by jamiedawsonyoung** [comment]
@matthewpaulthomas Could you have a look and +1 this please too.

**Comment by nottrobin** [comment]
#305 may become relevant.

**Comment by jamiedawsonyoung** [comment]
Reviewed with @matthewpaulthomas (and got +1) so the spec is below: 

### Sign in
- Styling as current build

### Signed in
Avatar from GitHub
- height: 24px
- width: 24px
- border-radius: 12px 
- padding: 10px

Username from GitHub
- Text color: $color-mid-dark
- Font size: 14px
- padding: 10px

*Let me know if you need any more styling*

**Comment by jamiedawsonyoung** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [#318 Three adjacent header elements look the same, behave differently](https://trello.com/c/CI8zpkRN/595-318-three-adjacent-header-elements-look-the-same-behave-differently)

**Comment by magdalena-mirowicz** [comment]
possibly reduce to simpler solution for the launch @matthewpaulthomas - to be discussed in standup

**Comment by magdalena-mirowicz** [comment]
should be solved by #305
