### ISSUE TITLE
[Add repos] pagination updates/fixes

### ISSUE THREAD

**Issue by nottrobin** [canonical-web-and-design/build.snapcraft.io#319]
---

Copied from Trello card: https://trello.com/c/zo4K32pj/143-add-repos-pagination-updates-fixes
Labels:

**Comment by matthewpaulthomas** [comment]
In Trello, Jamie wrote:
> ![pagination-proposal](https://cloud.githubusercontent.com/assets/19801137/23611882/f818d716-0270-11e7-8781-52041b8af25a.png)
> [This] is a visual of the styles listed below:
>
> Font size and line height: paragraph
> Text color: $color-dark
> Link style: regular
> Disabled link: Opacity: 0.5
>
> Selected item font style: Strong
>
> Divider character: U+007C
> Divider color: $color-mid-light
> Divider font size and line height: paragraph
> Divider left and right margin: 8px

**Comment by solazio** [comment]
This is fixed
