### ISSUE TITLE
[dashboard] “Not configured”, “Not registered” not keyboard-accessible

### ISSUE THREAD

**Issue by nottrobin** [canonical-web-and-design/build.snapcraft.io#332]
- You can use the keyboard to access the name and latest build columns. 

- **You cannot access "configured" or "Registered for publishing" columns.**

---

Copied from Trello card: https://trello.com/c/biaTTMzg/269-dashboard-not-configured-not-registered-not-keyboard-accessible
Labels: Bug

**Comment by solazio** [comment]
Not relevant for snapcraft.io, closing
