### ISSUE TITLE
[dashboard] Name field ignores capitals rather than lower-casing them [1]

### ISSUE THREAD

**Issue by nottrobin** [canonical-web-and-design/build.snapcraft.io#333]
Change any capitalization in a new snap name to lowercase automatically rather than ignoring the letter.

---

Copied from Trello card: https://trello.com/c/neb5XH0L/260-dashboard-name-field-ignores-capitals-rather-than-lower-casing-them
Labels: design

**Comment by matthewpaulthomas** [comment]
Bartek wrote in Trello:
> As far as I remember current 'quick' implementation simply uses browser input field pattern feature to limit allowed characters (meaning only lowercase characters and hyphens are allowed by the browser).
>
>This needs to be changed to a custom JavaScript validation that will handle changing the case of letters.

**Comment by matthewpaulthomas** [comment]
According to Firefox, it isn’t using the HTML pattern attribute:
&lt;input class="repositoryRow__snapNameInput___t0t7D" value="" type="text"&gt;
