### ISSUE TITLE
[Bug] Over-long snap names mess up the table

### ISSUE THREAD

**Issue by nottrobin** [canonical-web-and-design/build.snapcraft.io#334]
![](https://cloud.githubusercontent.com/assets/19801137/23612140/245d23f8-0272-11e7-8d97-26a7e22bcdfa.png)

It may save time to fix this at the same time as #793, the equivalent for repo names.

----

Copied from Trello card: https://trello.com/c/nbQSaI1h/213-bug-over-long-snap-names-mess-up-the-table
Labels:

**Comment by matthewpaulthomas** [comment]
![snapcraft-name-overlong](https://cloud.githubusercontent.com/assets/19801137/23612140/245d23f8-0272-11e7-8d97-26a7e22bcdfa.png)

**Comment by solazio** [comment]
Not relevant for snapcraft.io, closing
