### ISSUE TITLE
Bullet points are lopsided to the left

### ISSUE THREAD

**Issue by nottrobin** [canonical-web-and-design/build.snapcraft.io#339]
The bullet points (“Scale to millions of installs”, Available on all clouds”, etc) are imbalanced towards the left side of the page.

The dotted lines let the row have some sort of structure, by showing that the container is centered, but it would be good if we didn't need the dotted lines.

One way of making this look better would be reducing the width of the container.

---

Copied from Trello card: https://trello.com/c/BRHbNTrA/275-bullet-points-are-lopsided-to-the-left
Labels: design

**Comment by solazio** [comment]
Not relevant for snapcraft.io, closing
