### ISSUE TITLE
Feed API for new GitHub logins on build.snapcraft.io

### ISSUE THREAD

**Issue by nottrobin** [canonical-web-and-design/build.snapcraft.io#340]
Once we've launched we'll want to track who is registering. Please may we have an API that lists the GitHub accounts that have been connected and when this occurred.

---

Copied from Trello card: https://trello.com/c/ql4SsSxi/206-feed-api-for-new-github-logins-on-build-snapcraft-io
Labels:

**Comment by solazio** [comment]
Not relevant for snapcraft.io, closing
