### ISSUE TITLE
Non-obvious feedback when “Configured” status changes

### ISSUE THREAD

**Issue by nottrobin** [canonical-web-and-design/build.snapcraft.io#341]
From Colin in https://trello.com/c/58b036a0a703f3c476f4052e via https://trello.com/c/MSTYY4fr: “just clos[ing] the tab [after committing snapcraft.yaml on github.com] may not be obvious enough”.

The same problem will occur when you commit snapcraft.yaml any other way, and we detect it https://trello.com/c/ZhOfeleQ: just changing “✘ Not configured” to “✔” probably isn’t enough. Maybe we should flash the cell, and/or play a subtle sound effect.

---

Copied from Trello card: https://trello.com/c/bjCH1Jpj/304-non-obvious-feedback-when-configured-status-changes
Labels:

**Comment by matthewpaulthomas** [comment]
It _might_ turn out that the general feedback for “this table cell changed” (#663) is enough. Or it might turn out that changes to snapcraft.yaml in particular need more feedback.

**Comment by solazio** [comment]
Not relevant for snapcraft.io, closing
