### ISSUE TITLE
Can we have a light strip behind the avatar info

### ISSUE THREAD

**Issue by nottrobin** [canonical-web-and-design/build.snapcraft.io#352]
To let the user info define it's own space on the dashboard can we add a [light strip](https://docs.vanillaframework.io/en/patterns/strip) behind it. This will help with the spacing too.

---

Copied from Trello card: https://trello.com/c/zfOPTBX7/277-can-we-have-a-light-strip-behind-the-avatar-info
Labels: design

**Comment by matthewpaulthomas** [comment]
As I described in #223, it’s looking more likely that we’ll get rid of the avatar info altogether. This is because it will be redundant with the icon+ID in the header, and because we need the vertical space for the “Add repos” dialog to fit on screen below the first-time diagram+text.

**Comment by solazio** [comment]
Not relevant for snapcraft.io, closing
