### ISSUE TITLE
Top of page looks insubstantial — little text

### ISSUE THREAD

**Issue by nottrobin** [canonical-web-and-design/build.snapcraft.io#359]
You have to scroll down a couple thousand pixels before you get to anything resembling a paragraph. And even then, the paragraph is about snaps, not this site in particular. This makes it seem more like a poster than a brochure.

---

Copied from Trello card: https://trello.com/c/dOjbIOBp/273-top-of-page-looks-insubstantial-little-text
Labels: design

**Comment by jamiedawsonyoung** [comment]
This is going to be covered by #361

**Comment by jamiedawsonyoung** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Top of page looks insubstantial — little text #359](https://trello.com/c/taaI8on3/603-top-of-page-looks-insubstantial-little-text-359)

**Comment by solazio** [comment]
Not relevant for snapcraft.io, closing
