### ISSUE TITLE
Unauthorized to Publish Snap

### ISSUE THREAD

**Issue by nhandler** [canonical-web-and-design/build.snapcraft.io#370]
I have previously been publishing the `packer` snap from https://code.launchpad.net/~nhandler/+snap/packer . I am currently attempting to migrate the Git repository to https://github.com/nhandler/packer-snap and use build.snapcraft.io to build it. I have added the Github repository, and it shows up on https://build.snapcraft.io/dashboard. However, when I click `Sign in...` and attempt to use the name `packer` for publishing, I get an `Unauthorized` error. I am assuming the issue is related to the Ubuntu SSO (I am never presented with the typical login screen).

**Comment by evandandrea** [comment]
I think this is a duplicate of #290.

**Comment by solazio** [comment]
This is fixed, closing
