### ISSUE TITLE
Increase github repo list page size to 100

### ISSUE THREAD

**Issue by nottrobin** [canonical-web-and-design/build.snapcraft.io#379]
Comments:

I think this should be done only once the “Cancel” and “Add” buttons are fixed so that they’re always visible. Otherwise, if you selected a repo near the top of the list, you’d then need to scroll a long way to find the “Add” button.

---
Creator: Robin Winslow
Assignees: 
Copied from Trello card: https://trello.com/c/GpGhzKv3/171-add-new-repo-consider-design-to-increase-github-repo-list-page-size-to-100
Labels: Question,copy to github

**Comment by matthewpaulthomas** [comment]
[As wireframed](https://docs.google.com/document/d/1koTwI3cRr2S2vj5zHKKbR7aWxLRfShDVq2gHQ29cDyU/edit#heading=h.43owh6tjv12q), the dialog does not require any design changes if the batch size increases: the list is in a scrolling panel, with the title and buttons being separate panels.

**Comment by evandandrea** [comment]
@matthewpaulthomas do we need an issue for that? Right now it's not in a scrolling panel.

**Comment by solazio** [comment]
Not relevant for snapcraft.io, closing
