### ISSUE TITLE
Expose a bit more of errors from LP

### ISSUE THREAD

**Issue by nottrobin** [canonical-web-and-design/build.snapcraft.io#380]
"BadRequestPackageUploadResponse: 404 Client Error: Not Found" is still ugly and user-inscrutable but would at least be a bit more helpful to developers than "BadRequestPackageUploadResponse".

Comments:

---
Creator: Robin Winslow
Assignees: 
Copied from Trello card: https://trello.com/c/lDHtFcwJ/41-expose-a-bit-more-of-errors-from-lp
Labels: Question,copy to github

**Comment by katiefenn** [comment]
C: 2 
K: 1
B: 2

**Comment by solazio** [comment]
Not relevant for snapcraft.io, closing
