### ISSUE TITLE
Error state for too-frequent name registrations [1]

### ISSUE THREAD

**Issue by nottrobin** [canonical-web-and-design/build.snapcraft.io#381]
The Store has frequency limit on registering snaps - currently one/minute (maybe soon ten per ten minutes). We need to explain what’s happened if you hit the limit.

https://docs.google.com/document/d/1koTwI3cRr2S2vj5zHKKbR7aWxLRfShDVq2gHQ29cDyU

Comments:

---
Creator: Robin Winslow
Assignees: 
Copied from Trello card: https://trello.com/c/FZLKkSoJ/199-error-state-for-too-frequent-name-registrations
Labels: copy to github

**Comment by matthewpaulthomas** [comment]
As it turns out, [I had already specified the text for this](https://docs.google.com/document/d/1koTwI3cRr2S2vj5zHKKbR7aWxLRfShDVq2gHQ29cDyU/edit#heading=h.sf9bdlnfvbkg): “Whoa there! You’re registering names too quickly. Go do something else for a bit, then try again.”

**Comment by solazio** [comment]
This is not relevant for snapcraft.io
