### ISSUE TITLE
Robustness: authenticated proxy issues

### ISSUE THREAD

**Issue by nottrobin** [canonical-web-and-design/build.snapcraft.io#384]
We use an authenticated proxy to grant snap builds access to the network without also granting other builds access.  This works fine for many snaps but it goes wrong in particular for Java, where the language runtime has terrible support for authenticated proxies.

Virtually everything supports proxies per se just fine, though, so we could make this a lot better by interposing an unauthenticated local proxy which adds the necessary credentials before passing requests through to the real proxy and thence to the network.

Comments:

@magdalena_mir like all my robustness cards, it is still valid.,@colinwatson4  is it still valid? If not please move to done

---
Creator: Robin Winslow
Assignees: Colin Watson
Copied from Trello card: https://trello.com/c/DMCoCGyg/66-robustness-authenticated-proxy-issues
Labels: copy to github

**Comment by solazio** [comment]
No relevant for snapcraft.io, closing
