### ISSUE TITLE
API for progress by GitHub user

### ISSUE THREAD

**Issue by nottrobin** [canonical-web-and-design/build.snapcraft.io#385]
Once we have launched, we'll want to track how far GitHub users have made it through the journey.

Please may we have an API that lets us see whether:

- A GitHub user has connected to build.snapcraft.io
- They've enabled any repos
- For each repo, they've added the yaml
- For each repo, they've registered the name

Comments:

---
Creator: Robin Winslow
Assignees: 
Copied from Trello card: https://trello.com/c/CkjeKfIk/208-api-for-progress-by-github-user
Labels: copy to github

**Comment by solazio** [comment]
No relevant for snapcraft.io, closing
