### ISSUE TITLE
Attach landscape and canonical-livepatch to new switch units automatically

### ISSUE THREAD

**Issue by nottrobin** [canonical-web-and-design/build.snapcraft.io#387]
Both staging and production have had golive run on them, but this doesn't apply to new switch units; I've been running `juju add-relation $app landscape && juju add-relation $app canonical-livepatch` manually, but obviously that doesn't scale.

Comments:

@magdalena_mir still valid,@colinwatson4  is it still valid? If not please move to done

---
Creator: Robin Winslow
Assignees: 
Copied from Trello card: https://trello.com/c/QHrUGBL1/40-attach-landscape-and-canonical-livepatch-to-new-switch-units-automatically
Labels: copy to github

**Comment by solazio** [comment]
Not relevant for snapcraft.io
