### ISSUE TITLE
Show latest build according to priority

### ISSUE THREAD

**Issue by nottrobin** [canonical-web-and-design/build.snapcraft.io#388]
Currently we take latest build as the newest.

We should take status priority into consideration as described in design doc ("Repos to build and publish" section)

https://docs.google.com/document/d/1koTwI3cRr2S2vj5zHKKbR7aWxLRfShDVq2gHQ29cDyU

Comments:

@matthewpaulthomas Please clarify this with developers. Thanks,@magdalena_mir Please see the linked specification, which describes the desired behaviour in detail.,@bartoszopka in what situation would the latest build not be newest? @matthewpaulthomas 

---
Creator: Robin Winslow
Assignees: 
Copied from Trello card: https://trello.com/c/77zaPCXG/152-show-latest-build-according-to-priority
Labels: copy to github

**Comment by matthewpaulthomas** [comment]
(Magda may not have realized that Colin had posted “the linked specification … describes the desired behaviour in detail” one minute before she requested “Please clarify this with developers”. And I see no questions either here or in the Trello card. If anything does need clarifying, please be more specific.)

**Comment by solazio** [comment]
No relevant for snapcraft.io, closing
