### ISSUE TITLE
Editing and committing snapcraft.yaml within build.snapcraft.io

### ISSUE THREAD

**Issue by nottrobin** [canonical-web-and-design/build.snapcraft.io#390]
From Peter in https://trello.com/c/58b036a0a703f3c476f4052e via https://trello.com/c/MSTYY4fr: “editing file in BSI UI is much bigger task that would be best treated separately.”

Comments:

---
Creator: Robin Winslow
Assignees: Matthew Paul Thomas
Copied from Trello card: https://trello.com/c/9sTd13vi/305-editing-and-committing-snapcraft-yaml-within-build-snapcraft-io
Labels: copy to github

**Comment by solazio** [comment]
Not relevant for snapcraft.io
