### ISSUE TITLE
Add button on select-repositories active before selecting any repos

### ISSUE THREAD

**Issue by nottrobin** [canonical-web-and-design/build.snapcraft.io#392]
Comments:

**Steps to reproduce:**

1. Click Add repos… on the dashboard

**What happens:**

* The Add button is active
* Clicking it does nothing

**What should happen:**

* The Add button is disabled until a repository is selected

---
Creator: Robin Winslow
Assignees: 
Copied from Trello card: https://trello.com/c/o3hIYI6N/347-add-button-on-select-repositories-active-before-selecting-any-repos
Labels: Bug,copy to github

**Comment by solazio** [comment]
No relevant for snapcraft.io, closing
