### ISSUE TITLE
[dashboard] Repo still listed after being deleted on GitHub

### ISSUE THREAD

**Issue by nottrobin** [canonical-web-and-design/build.snapcraft.io#398]
So template snapcraft.yaml 404s

Comments:

---
Creator: Robin Winslow
Assignees: 
Copied from Trello card: https://trello.com/c/DA55xmX4/270-dashboard-repo-still-listed-after-being-deleted-on-github
Labels: Bug,copy to github

**Comment by bartaz** [comment]
Also (as mentioned in #859) if repo is deleted in GH it cannot be removed from BSI.

**Comment by matthewpaulthomas** [comment]
I guess there will always be some cases where BSI doesn’t get around to removing a repo automatically before you try and remove it manually. So maybe the issues are separate after all?

**Comment by solazio** [comment]
No relevant for snapcraft.io, closing
