### ISSUE TITLE
[Bug] “Add repos” > “Cancel” > needless table reloading

### ISSUE THREAD

**Issue by nottrobin** [canonical-web-and-design/build.snapcraft.io#400]
1\. Go to the Dashboard.
2\. Choose “Add repos”.
3\. Choose “Cancel”.

What happens:

1\. There is a spinner while the table loads.
3\. There is a spinner while the table reloads.

What should happen:

3\. Since you haven’t changed the contents of the table, it shouldn’t need to reload.

Comments:

---
Creator: Robin Winslow
Assignees: 
Copied from Trello card: https://trello.com/c/Ja8ZN2Z3/306-bug-add-repos-cancel-needless-table-reloading
Labels: copy to github

**Comment by solazio** [comment]
No relevant for snapcraft.io, closing
