### ISSUE TITLE
Filterable list component

### ISSUE THREAD

**Issue by nottrobin** [canonical-web-and-design/build.snapcraft.io#405]
Comments:

@katie_fenn is it still valid? If not please move to done,Is this the same as search? And if not, how? https://trello.com/c/YEILhCOS

---
Creator: Robin Winslow
Assignees: 
Copied from Trello card: https://trello.com/c/GgHar1iZ/81-filterable-list-component
Labels: Question,copy to github

**Comment by matthewpaulthomas** [comment]
If this is filtering the “Add repos” dialog, it’s a duplicate of #330. Alternatively, it might be filtering the “My repos” list.

**Comment by solazio** [comment]
No relevant for snapcraft.io, closing
