### ISSUE TITLE
Nagios monitoring, PagerDuty, etc.

### ISSUE THREAD

**Issue by nottrobin** [canonical-web-and-design/build.snapcraft.io#407]
Comments:

@magdalena_mir yes,@colinwatson4 is this still valid? thanks

---
Creator: Robin Winslow
Assignees: Colin Watson
Copied from Trello card: https://trello.com/c/C7EK03aw/52-nagios-monitoring-pagerduty-etc
Labels: copy to github

**Comment by solazio** [comment]
No relevant for snapcraft.io, closing
