### ISSUE TITLE
Repository state caching

### ISSUE THREAD

**Issue by nottrobin** [canonical-web-and-design/build.snapcraft.io#409]
At the moment we query the GitHub API for  repository data on every request. This prevents us from having stateful interfaces, and storing data on the presence of snapcraft.yaml files.

cjwatson suggested caching this information in memcached as a basic first-step in making the application stateful.

Comments:

@katie_fenn Is this still relevant?

---
Creator: Robin Winslow
Assignees: 
Copied from Trello card: https://trello.com/c/rZQP8vTU/87-repository-state-caching
Labels: Question,copy to github

**Comment by solazio** [comment]
No relevant for snapcraft.io, closing
