### ISSUE TITLE
Propagate OOPS IDs from LP

### ISSUE THREAD

**Issue by nottrobin** [canonical-web-and-design/build.snapcraft.io#410]
Comments:

@magdalena_mir yes,@colinwatson4 is this still valid? thanks

---
Creator: Robin Winslow
Assignees: 
Copied from Trello card: https://trello.com/c/eIVBdEpN/42-propagate-oops-ids-from-lp
Labels: copy to github

**Comment by katiefenn** [comment]
C: 2,
K: 2,
R: 2,
B: 2

**Comment by solazio** [comment]
Not relevant for snapcraft.io
