### ISSUE TITLE
[dashboard to ubuntu sign in] redirect page build

### ISSUE THREAD

**Issue by nottrobin** [canonical-web-and-design/build.snapcraft.io#413]
https://docs.google.com/document/d/1koTwI3cRr2S2vj5zHKKbR7aWxLRfShDVq2gHQ29cDyU/edit#heading=h.sf9bdlnfvbkg

Comments:

@katie_fenn  is it still valid? If not please move to done,Is this still blocked? I’m not sure what it’s referring to.,Blocked by provision of design documents.

---
Creator: Robin Winslow
Assignees: 
Copied from Trello card: https://trello.com/c/h7TancwG/99-dashboard-to-ubuntu-sign-in-redirect-page-build
Labels: Blocked,Question

**Comment by solazio** [comment]
No relevant for snapcraft.io, closing
