### ISSUE TITLE
Performance audit

### ISSUE THREAD

**Issue by nottrobin** [canonical-web-and-design/build.snapcraft.io#421]
Leading on from #281, we should do a general performance audit to check which parts of the application are particularly slow.

**Comment by katiefenn** [comment]
Help wanted: needs prioritising

**Comment by cjwatson** [comment]
C: 2

**Comment by bartaz** [comment]
B: 4

**Comment by earnubs** [comment]
See also https://github.com/garbles/why-did-you-update

**Comment by solazio** [comment]
No relevant for snapcraft.io, closing
