### ISSUE TITLE
Create script to help macOS users get connected to APIs

### ISSUE THREAD

**Issue by nottrobin** [canonical-web-and-design/build.snapcraft.io#423]
Leading on from discussion about #277

**Comment by cjwatson** [comment]
I think it's more that we should make the existing script work on macOS.  This is probably a matter of making sure the relevant LPish Python modules are up-to-date on PyPI.

**Comment by katiefenn** [comment]
Help wanted: needs prioritising

**Comment by cjwatson** [comment]
C: 3

**Comment by solazio** [comment]
Not relevant for snapcraft.io
