### ISSUE TITLE
GitHub user icon in header

### ISSUE THREAD

**Issue by matthewpaulthomas** [canonical-web-and-design/build.snapcraft.io#426]
[From the spec](https://docs.google.com/document/d/1koTwI3cRr2S2vj5zHKKbR7aWxLRfShDVq2gHQ29cDyU/edit#heading=h.qofgt54r0olr):
> ![header-signed-in-general](https://cloud.githubusercontent.com/assets/19801137/23656223/ad702974-0330-11e7-9bec-581de4b96c95.png)
> When you’re signed in, the header should also include your GitHub avatar.

Besides making the site slightly friendlier, this would also help fix #318.

**Comment by solazio** [comment]
No relevant for snapcraft.io, closing
