### ISSUE TITLE
Deleting a snap from the dashboard, after deleting the github repo, causes snap list to disappear

### ISSUE THREAD

**Issue by earnubs** [canonical-web-and-design/build.snapcraft.io#453]
![delete](https://cloud.githubusercontent.com/assets/167440/23767723/86572752-0501-11e7-867e-a14fbdda78f2.gif)

Steps to reproduce:

* Add repo to dashboard
* Delete repo in github
* Delete repo in dashboard

**Comment by evandandrea** [comment]
For what it's worth, I tried a few different ways on staging and production but could not reproduce the issue.

**Comment by earnubs** [comment]
It was not because it was "unconfigured" but because the repo had been deleted in Github.

**Comment by evandandrea** [comment]
Ah, apologies for misreading.

**Comment by matthewpaulthomas** [comment]
Fixing #398 might not fix this issue, but at the least it would make it much less likely to occur.

**Comment by solazio** [comment]
Not relevant for snapcraft.io
