### ISSUE TITLE
Consistent UI for registering and changing snap name

### ISSUE THREAD

**Issue by bartaz** [canonical-web-and-design/build.snapcraft.io#468]
Currently registering new name and changing registered name have a little bit different UI (one uses 'inline' input in the table, the other has an input inside of the dropdown).

[As discussed in spec doc](https://docs.google.com/a/canonical.com/document/d/1koTwI3cRr2S2vj5zHKKbR7aWxLRfShDVq2gHQ29cDyU/edit?disco=AAAAA8nSKX0) by @matthewpaulthomas:
> However, I do agree that it would be good for the initial-registration UI and the renaming UI to have their text fields in a consistent place. So in the long run, I think we should move the initial-registration field from the table cell into the revealed panel as well.

This card covers updating design spec (and possibly wireframes) of registering new name UI and implementation of the changes.

**Comment by matthewpaulthomas** [comment]
[Specification updated](https://docs.google.com/document/d/1koTwI3cRr2S2vj5zHKKbR7aWxLRfShDVq2gHQ29cDyU/edit#bookmark=id.bedjrhkea4m4). The design for registering a name now has the text field inside the revealed panel, rather than in the clicked cell.

**Comment by solazio** [comment]
No relevant for snapcraft.io, closing
