### ISSUE TITLE
Turn on arm64 builds

### ISSUE THREAD

**Issue by evandandrea** [canonical-web-and-design/build.snapcraft.io#473]
We support four kernels with Ubuntu Core: 32-bit and 64-bit x86, 32-bit and 64-bit ARM. Right now we build for 64-bit x86 and 32-bit ARM. We should enable 64-bit ARM builds so that snaps for the dragonboard 410c can be built.

I currently consider this a low priority.

**Comment by om26er** [comment]
Enablement of arm64 builds on build.snapcraft.io will be a welcome feature that will help us distribute, test and deploy our tool ([Crossbar](https://github.com/crossbario/crossbar/)) on an important platform.

**Comment by solazio** [comment]
We support arm64 in the `Builds` tab on snapcraft.io
