### ISSUE TITLE
Layout offset on Safari/iOS

### ISSUE THREAD

**Issue by squidsoup** [canonical-web-and-design/build.snapcraft.io#498]
Layout in Safari on iOS is a bit wonky, with a gutter on the right offsetting the page content. 

![homepage](http://i.imgur.com/vehlsWt.jpg)

UA: 
"Mozilla/5.0 (iPhone; CPU iPhone OS 10_3 like Mac OS X) AppleWebKit/603.1.30 (KHTML, like Gecko) Version/10.0 Mobile/14E5269a Safari/602.1

**Comment by solazio** [comment]
No relevant for snapcraft.io, closing
