### ISSUE TITLE
Polling even when user is not watching

### ISSUE THREAD

**Issue by bartaz** [canonical-web-and-design/build.snapcraft.io#508]
Currently on most of our views we are polling the server to keep data up to date.

Each 15s we send requests (sometimes many - especially on 'my repos').
Because we simply use intervals for that data is fetched always, even when user is not actively watching the page (has it open in one of the tabs in the browser).

It's a bit unnecessary.

We could try to use page visibility API or `requestAnimationFrame` (that is paused when page is not visible) to trigger data fetching.

**Comment by matthewpaulthomas** [comment]
If this change is easy, and easily reversible, by all means do it. But once it’s possible to see partial build logs (#295), people might leave build pages open in the background, waiting for the build to complete. For the benefit of those people, we might change the title and/or bookmark icon of each build page to reflect its status. That wouldn’t work if background pages weren’t updating.

Have you considered using a push system instead, such as [SSE or WebSockets](http://streamdata.io/blog/push-sse-vs-websockets/)?

**Comment by bartaz** [comment]
> If this change is easy, and easily reversible, by all means do it.

It's not a 'trivial' change and would require some changes to implementation of our polling mechanism. But also it wouldn't mean that implementing it would prevent us from updating some status in inactive tab if we want to.
But I guess, by default, we shouldn't be sending requests when user is not actively looking at the tab. When user get's back, the view should be updated.

> Have you considered using a push system instead, such as SSE or WebSockets?

Yes and no. While of course using some push system would help in this regard we didn't have time to invest into it. Especially that we rely mostly on external API (GitHub and LP), so we would need those systems (LP for snaps/builds statuses especially) support such approach. While we may be getting closer to making it possible (as LP has some webhook support added now to communicate with BSI) it will be a significant change (compared to fairy simple preventing polling when tab is inactive).

**Comment by cjwatson** [comment]
I agree with @bartaz's remarks.  It's also worth noting that polling the page for a single build is considerably cheaper than polling some other pages ("My repos" in particular), so we could reasonably carry on polling in just that case.

**Comment by earnubs** [comment]
I looked at SSE's for snapweb, they're not supported widely enough yet I don't think http://caniuse.com/#feat=eventsource

**Comment by solazio** [comment]
Not relevant for snapcraft.io
