### ISSUE TITLE
Consider presenting the snap app icon

### ISSUE THREAD

**Issue by evandandrea** [canonical-web-and-design/build.snapcraft.io#510]
We do not currently show the icon (`icon:` property or `meta/gui/icon.png`) of the application associated with a repo anywhere on build.snapcraft.io. I've filed this issue to discuss whether we should.

The icon is presented in snapweb, on the community site [uappexplorer](https://uappexplorer.com/apps?type=snappy), and in GNOME Software.

**Comment by matthewpaulthomas** [comment]
Yes! It would make repos easier to find in the table, thereby rewarding good behavior. And it would make the repo page more interesting.

Is it possible to set the icon independently of the repo/snapcraft.yaml, for example in the store UI itself?

**Comment by evandandrea** [comment]
@matthewpaulthomas it is possible to set `snapcraft.yaml` metadata like the icon in MyApps, but doing so will make the store prefer that over anything you do in `repo/snapcraft.yaml` *forever*. There are a few bugs around that. The icon one [is here](https://bugs.launchpad.net/snapstore/+bug/1672660).

Setting metadata should happen where you collaboratively review changes to your project: GitHub.

**Comment by solazio** [comment]
No relevant for snapcraft.io, closing
