### ISSUE TITLE
Rendering HTML error response from Launchpad

### ISSUE THREAD

**Issue by bartaz** [canonical-web-and-design/build.snapcraft.io#533]
When LP API returns error as HTML rather then JSON we render whole escaped HTML contents instead of error message.

<img width="1093" alt="screen shot 2017-03-23 at 09 30 44" src="https://cloud.githubusercontent.com/assets/83575/24238743/9b6fbd5c-0fab-11e7-81a8-26fd7ce11590.png">

In this case LP API to create new snap returned 503 Service Unavailable.

**Comment by bartaz** [comment]
Another case when it happened:

<img width="1053" alt="screen shot 2017-04-21 at 08 09 50" src="https://cloud.githubusercontent.com/assets/83575/25264877/1ab3618e-266a-11e7-8580-d010733fd8c9.png">

**Comment by evandandrea** [comment]
As they won't know what Launchpad is, could we have a generic message for an error to communicate with the service?

**Comment by matthewpaulthomas** [comment]
I don’t understand either of these screenshots.

The first one seems to show an error message next to the name of a repo in the “Add repos” dialog. But, currently, nothing is ever supposed to appear in that position.

The second screenshot shows an error message between the main heading and the build table on a build page. But, again, nothing is ever supposed to appear there.

**Comment by bartaz** [comment]
@matthewpaulthomas 

First one is likely the result of legacy code - in prototype phase we were showing status per repository. In this case I guess if LP returns HTML error when asking for builds of given repo (which we do ask for to show progress meter) it ends like this.

Second one - also a generic code for handling errors - if we get any error when calling APIs for the build we show error message on top of the table. In this case error we got was HTML instead of JSON (again due some LP failure).

This issue is mainly that we don't handle such cases in a good way and they result in such unexpected screenshots.

**Comment by matthewpaulthomas** [comment]
If I understand correctly, then, the first case can be fixed simply by deleting code.

For the second case, if there’s an error getting the status of a build, that should be shown in the “Result” cell for that build, not above the entire table. Is that reasonable? [Spec updated](https://docs.google.com/document/d/1koTwI3cRr2S2vj5zHKKbR7aWxLRfShDVq2gHQ29cDyU/edit#heading=h.ii93oqyp8hl8): “Connection error”.

**Comment by bartaz** [comment]
Yes, in these particular places this should solve the issue.

But I think when fixing that we should approach it in general not assuming all error responses from APIs will be JSON and handle it properly everywhere in the app - not allowing such HTML errors leak in UI.

**Comment by matthewpaulthomas** [comment]
True. That build status case is only the second place, so far, where I’ve specced what should happen when receiving an error from an external service. There will be dozens more cases, given how much this app communicates with GitHub, Launchpad, SSO, and the snap store. I guess each of those should be separate issue reports, leaving this one for a general solution to failing quietly rather than verbosely.

**Comment by evandandrea** [comment]
See also #691

**Comment by solazio** [comment]
No relevant for snapcraft.io, closing
