### ISSUE TITLE
"All set up…" and progress bar briefly appear

### ISSUE THREAD

**Issue by evandandrea** [canonical-web-and-design/build.snapcraft.io#549]
**To reproduce:**

* After going through the first-time flow, add an additional repository.
* Add a snapcraft.yaml and register the snap name.

**What happens:**

* "All set up…" and the first-time flow progress bar briefly appear (~1-2s).

This is confusing. I'm shown progress for steps unrelated to my current task.

**What should happen:**

* Neither the "All set up…" message nor the first-time flow progress bar appear.

**Comment by solazio** [comment]
No relevant for snapcraft.io, closing
