### ISSUE TITLE
Removing repo doesn't update in IE on Windows

### ISSUE THREAD

**Issue by popey** [canonical-web-and-design/build.snapcraft.io#550]
Logged in on Windows 10 / IE 11 and tried to remove an old repo. When I hit the red remove button nothing appears to happen on screen. However if I visit the same dashboard in another browser I can see the repo has indeed been deleted.

![screenshot 4](https://cloud.githubusercontent.com/assets/1841272/24397430/1f7a245c-139e-11e7-8744-124f2a96b1d7.png)
![screenshot 5](https://cloud.githubusercontent.com/assets/1841272/24397434/22cc1e44-139e-11e7-90a4-8e2d960ecfe2.png)

**Comment by popey** [comment]
In fact this seems to be a general page update issue in IE11. If I add a repo I can select the repo from the list but when I come back to "My Repos" it's not listed until I force-refresh the browser.

**Comment by popey** [comment]
Similarly when registering a name successfully you get bounced back to a page which says "Not registered" as if you'd not gone through the name registration process at all. Again. CTRL+F5 (force refresh) updates the page.

**Comment by matthewpaulthomas** [comment]
At the risk of confusing cause and effect … Currently 1.61% of build.snapcraft.io visitors are using Internet Explorer.

**Comment by solazio** [comment]
This is fixed in the `Builds` tab on snapcraft.io
