### ISSUE TITLE
Some distro logos are squished Win10 / IE11

### ISSUE THREAD

**Issue by popey** [canonical-web-and-design/build.snapcraft.io#551]
See fedora and arch logos in the screenshot 

![screenshot 3](https://cloud.githubusercontent.com/assets/1841272/24397471/3efa833a-139e-11e7-9323-de291883c094.png)

**Comment by earnubs** [comment]
Consider setting @height on brandLogos

**Comment by solazio** [comment]
No relevant for snapcraft.io, closing
