### ISSUE TITLE
Developer Agreement fails when registering name with long username

### ISSUE THREAD

**Issue by bartaz** [canonical-web-and-design/build.snapcraft.io#570]
Accepting Developer Agreement when registering name fails as Forbidden when username is longer then 20 characters.

When we are dealing with a Ubuntu One user who didn't accept Developer Agreement yet and doesn't have a short namespace set in the store we try to set the namespace automatically using their user name.

If the user name is longer then 20 characters setting the namespace fails and name registration is not possible:

`PATCH account` request results with "Short namespace must be no longer than 20 characters." error.

**Comment by evandandrea** [comment]
This seems like a bug in the store. As I understand it, the plan is to ultimately drop developer namespaces for SSO usernames. These seemingly have no limit (or the limit is beyond the 100 characters that I tried).

GitHub usernames have a limit of 39 characters.

**Comment by evandandrea** [comment]
Filed as [LP: #1678958](https://bugs.launchpad.net/snapstore/+bug/1678958).

**Comment by solazio** [comment]
No relevant for snapcraft.io, closing
