### ISSUE TITLE
the unclickable cells are more colorful overall than the clickable one

### ISSUE THREAD

**Issue by jamiedawsonyoung** [canonical-web-and-design/build.snapcraft.io#607]
We need to make sure this is tested when we do testing… 

_From Google Docs_

> Look at the penultimate row: there are three cells with ✔, but only the first two are clickable. How can you tell the third is not? …Its … text is green? That’s the only clear difference. The down arrows ⌵ are a good move, but it’s still the case that the unclickable cells are more colorful overall than the clickable ones.

**Comment by solazio** [comment]
Not relevant for snapcraft.io, closing
