### ISSUE TITLE
"Invalid association handle" when signing in

### ISSUE THREAD

**Issue by popey** [canonical-web-and-design/build.snapcraft.io#623]
Ubuntu 16.04, chrome 57 latest, incognito window (doing testing).

Tried to register a name for a snap, took me through the SSO sign in and 2fa dance. When I got back, I had a red bar and "Invalid association handle" in it. Possibly related to / duplicate of #552 

![image](https://cloud.githubusercontent.com/assets/1841272/24909202/ddf60e74-1eba-11e7-8e3e-b839961cb93b.png)

**Comment by evandandrea** [comment]
This happened to @sergiusens [as well](https://forum.snapcraft.io/t/error-on-login-on-build-snapcraft-io/678).

**Comment by bartaz** [comment]
I did some testing/debugging to reproduce this issue locally.

The error itself comes from openid node module that we use to handle the sign in: https://github.com/havard/node-openid/blob/master/openid.js#L1242-L1245

So it seems it only happens when association passed to openid callback is empty.
We store the association object [in the session](https://github.com/canonical-websites/build.snapcraft.io/blob/master/src/server/openid/relyingparty.js#L16-L20) and that's what we [load back after sign-in](https://github.com/canonical-websites/build.snapcraft.io/blob/master/src/server/openid/relyingparty.js#L27-L31).
So the 'Invalid association handle' error showing up could mean that the session was lost for some reason during the login process.

I tried to verify this locally and I succeeded. Restarting BSI server (with in memory session) or restarting memcached server (with memcached session) during the sign-in caused "Invalid association handle" error to show up.

On production environment sessions are stored in memcached so restarting node server shouldn't affect the session storage. 
So it seems that the issue may be caused by some temporary memcached failure or something else affecting user session.

I'm not sure what more we can do at this point without being able to reproduce this issue deterministically on production or staging.
We could possibly introduce more detailed logging around openid login and session, so that when issue occurs again we can investigate more.

We may also implement a better UI for such errors, to help users go back to their task. Maybe we should allow them to sign-out and sign in again (hoping it will renew the session for the next try).

**Comment by bartaz** [comment]
Marking as blocked for now, until we decide how to proceed with this issue.

**Comment by evandandrea** [comment]
I've seen this several times today in Melbourne time (so doubtful that a rollout was happening at the same time). In each instance I was in private browsing mode, attempting to sign in with different SSO credentials.

<img width="797" alt="screen shot 2017-11-06 at 11 30 24" src="https://user-images.githubusercontent.com/1523179/32420924-8c5933cc-c2e6-11e7-9245-fa6920f1b6a1.png">

**Comment by evandandrea** [comment]
```
Request URL:https://build.snapcraft.io/login/verify?starting_url=https%3A%2F%2Fbuild.snapcraft.io%2Fuser%2Fevandandrea&caveat_id=%7B%22secret%22<REDACTED>%22version%22%3A%201%7D
Request Method:POST
Status Code:302 Found
Remote Address:162.213.33.209:443
Referrer Policy:no-referrer-when-downgrade
Response Headers
view source
Connection:Keep-Alive
Content-Length:70
Content-Type:text/html; charset=utf-8
Date:Mon, 06 Nov 2017 00:39:01 GMT
Keep-Alive:timeout=5, max=100
Location:/login/failed
Server:Apache/2.4.18 (Ubuntu)
set-cookie:sessionId=s%3APlFENH5Q1NJkc_JIlZ0VY4AfWVbEK6Lj.Ljn5xEK2qbjtSc7%2BqCF%2FklpAwXN9gIZzlft7CYBtxkE; Path=/; Expires=Mon, 06 Nov 2017 02:39:01 GMT; HttpOnly; Secure
Strict-Transport-Security:max-age=15768000; includeSubDomains; preload
Vary:Accept
X-Content-Type-Options:nosniff
X-DNS-Prefetch-Control:off
X-Download-Options:noopen
X-Frame-Options:SAMEORIGIN
X-Request-Id:Wf@vJH8AAQEAAFOf2KQAAACA1
X-VCS-Revision:7f90ac85b33014269f3e97686acaaffc3f131cd5
X-XSS-Protection:1; mode=block
Request Headers
view source
Accept:text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8
Accept-Encoding:gzip, deflate, br
Accept-Language:en-US,en;q=0.9
Cache-Control:max-age=0
Connection:keep-alive
Content-Length:2770
Content-Type:application/x-www-form-urlencoded
Cookie:sessionId=s%3APlFENH5Q1NJkc_JIlZ0VY4AfWVbEK6Lj.Ljn5xEK2qbjtSc7%2BqCF%2FklpAwXN9gIZzlft7CYBtxkE; _ga=GA1.2.145786247.1509926142; _gid=GA1.2.2092807224.1509926142; _ga=GA1.3.145786247.1509926142; _gid=GA1.3.2092807224.1509926142; _mkto_trk=id:066-EOV-335&token:_mch-build.snapcraft.io-1509926156537-27554; _gat=1; _gat_UA-1018242-4=1; _gat_UA-1018242-33=1; _dc_gtm_UA-1018242-59=1
DNT:1
Host:build.snapcraft.io
Origin:https://login.ubuntu.com
Referer:https://login.ubuntu.com/+openid?openid.mode=checkid_setup&openid.ns=http%3A%2F%2Fspecs.openid.net%2Fauth%2F2.0&openid.ns.sreg=http%3A%2F%2Fopenid.net%2Fextensions%2Fsreg%2F1.1&openid.sreg.required=nickname%2Cemail%2Cfullname&openid.ns.macaroon=http%3A%2F%2Fns.login.ubuntu.com%2F2016%2Fopenid-macaroon&openid.macaroon.caveat_id=%7B%22secret%22<REDACTED>%22version%22%3A%201%7D&openid.identity=http%3A%2F%2Fspecs.openid.net%2Fauth%2F2.0%2Fidentifier_select&openid.claimed_id=http%3A%2F%2Fspecs.openid.net%2Fauth%2F2.0%2Fidentifier_select&openid.assoc_handle=%7BHMAC-SHA256%7D%7B59ffaf22%7D%7BofECIw%3D%3D%7D&openid.return_to=https%3A%2F%2Fbuild.snapcraft.io%2Flogin%2Fverify%3Fstarting_url%3Dhttps%253A%252F%252Fbuild.snapcraft.io%252Fuser%252Fevandandrea%26caveat_id%3D%257B%2522secret%2522<REACTED>%2522version%2522%253A%25201%257D&openid.realm=https%3A%2F%2Fbuild.snapcraft.io
Upgrade-Insecure-Requests:1
User-Agent:Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/63.0.3239.30 Safari/537.36
Query String Parameters
view source
view URL encoded
starting_url:https://build.snapcraft.io/user/evandandrea
caveat_id:{"secret": "<REACTED>", "version": 1}
```

**Comment by evandandrea** [comment]
This is now reproducible for me:

1. I start a fresh private browsing session
2. Go to build.snapcraft.io
3. GitHub login as myself
4. Click a repo already on the dashboard and the SSO login button
5. Enter the credentials for the Snapcrafters SSO account
6. "Error:Invalid association handle"

**Comment by popey** [comment]
I also got this yesterday again. Seems I get this when I'm using a browser profile that I don't use often, so have to login again. My cookie will have timed out as I haven't used it in a while. So I'm effectively going through the same dance as @evandandrea does when he's in private browsing.

**Comment by bartaz** [comment]
It showed up again: #1054

**Comment by evandandrea** [comment]
I'm seeing this again and for the moment can reliably reproduce.
https://pastebin.canonical.com/p/QYf8yBsKq2/

**Comment by popey** [comment]
Still getting this today. I have tried to do this in firefox and chrome. Finally got it go after trying at least 5 times. Managed to get a screenshot of the developer tools in chrome. Looks like a 409 when calling `https://dashboard.snapcraft.io/dev/api/register-name/` 

![image](https://user-images.githubusercontent.com/1841272/39811845-326a0882-5382-11e8-9760-209c14b876b2.png)

The trigger for it happening is when clicking "Register name". The snap in question is registered under snapcrafters (snap-advocacy at canonical) and I am a collaborator (alan at popey). This problem successfully eats chunks of my day and makes me actively not use build.snapcraft.io but use launchpad instead. I can't imagine what this does for people outside the company!

**Comment by flexiondotorg** [comment]
I've got the same issue. I'm was trying to register the name for `sdlpop` via build.snapcraft.io. I'm logged into GitHub as myself (flexiondotorg) and signed into LP as myself (flexiondotorg).

**Comment by evandandrea** [comment]
![1f3c806f-fa91-4ac1-a766-faae3afd8df7](https://user-images.githubusercontent.com/1523179/39872298-73bf6ccc-545f-11e8-95bc-7c2489f75a87.png)

I’ve just seen this again.

**Comment by flexiondotorg** [comment]
I've just installed a snap of chromium (never had the chromium snap on this computer before) to configure some repos in build.snapcraft.io and immediately got the Invalid association handle. Now I see now repos at all.

![build-unauthorised](https://user-images.githubusercontent.com/304639/39881524-1836e118-5479-11e8-89e5-2ad72b41bd6a.png)

**Comment by flexiondotorg** [comment]
Just tried again and got some violations:

![violation](https://user-images.githubusercontent.com/304639/39882904-261a8b82-547d-11e8-8c96-3c548a7825a0.png)

And then `ERR_NETWORK_CHANGED`

![network-changed](https://user-images.githubusercontent.com/304639/39882921-35c4e46a-547d-11e8-8cf0-c3b29a2e1e05.png)

**Comment by evandandrea** [comment]
<img width="646" alt="screen shot 2018-05-11 at 09 51 58" src="https://user-images.githubusercontent.com/1523179/39915884-03365810-5501-11e8-81c1-36bf45199610.png">

Seeing it in a loop today.

**Comment by evandandrea** [comment]
<img width="444" alt="screen shot 2018-05-11 at 09 52 56" src="https://user-images.githubusercontent.com/1523179/39915924-1ed26046-5501-11e8-81da-065f0d163724.png">

And now this one.

**Comment by evandandrea** [comment]
<img width="366" alt="screen shot 2018-05-11 at 09 53 46" src="https://user-images.githubusercontent.com/1523179/39916296-f3e1559e-5501-11e8-8e69-a7b48be4135f.png">

Full response: https://pastebin.canonical.com/p/Fdz3cyyvff/

**Comment by popey** [comment]
Are we any closer to this being fixed? It's blocking our ability to use build.snapcraft.io full stop. We are now getting a backlog of snaps which we can't build because we cannot hook them up to the build service.

**Comment by bartaz** [comment]
I'm getting it myself today as well.

From log it seems like association handle is being saved to the session, but then (when SSO redirects back to BSI) it is not found in my session. So it's either nor properly saved or not available for some other reason.

Currenly our main suspect is memcached (which is used to store the session), but both memcached units seem operational, so we don't really know what may be the source of these issues.

```
2018-06-06 09:33:45.363Z INFO login "User successfully authenticated" 
2018-06-06 09:33:45.801Z INFO login "User info successfully fetched" 
2018-06-06 09:52:55.420Z INFO login "User successfully authenticated" 
2018-06-06 09:52:55.830Z INFO login "User info successfully fetched" 
2018-06-06 10:15:57.976Z INFO login "User successfully authenticated" 
2018-06-06 10:15:59.240Z INFO login "User info successfully fetched" 
2018-06-06 10:17:52.897Z INFO login "User successfully authenticated" 
2018-06-06 10:44:32.172Z INFO login "User successfully authenticated" 
2018-06-06 10:52:15.381Z INFO login "Saving association handle for user bartaz" 
2018-06-06 10:52:17.782Z ERROR login "No association handle found for user bartaz" 
2018-06-06 11:01:29.650Z INFO login "User successfully authenticated" 
2018-06-06 11:01:30.015Z INFO login "User info successfully fetched" 
2018-06-06 11:01:44.377Z ERROR login "No association handle found for user bartaz" 
2018-06-06 11:02:35.870Z INFO login "User successfully authenticated" 
2018-06-06 11:02:36.253Z INFO login "User info successfully fetched" 
2018-06-06 11:02:50.975Z INFO login "Saving association handle for user bartaz" 
```

**Comment by popey** [comment]
I'm getting this again today when trying to add a new snap to the store under my personal account.

**Comment by popey** [comment]
Got it again today. Used a private browsing session and made sure I was logged out of everything to sign back in cleanly.

**Comment by evandandrea** [comment]
I am seeing this continuously today.

**Comment by popey** [comment]
Getting it again today :( :( :(

**Comment by joedborg** [comment]
I'm also getting this.  Have to logout of GitHub and Ubuntu SSO, then re-sign in to fix.

**Comment by popey** [comment]
Still getting this...

**Comment by joedborg** [comment]
Getting this today.  The old way of signing out of everything and trying again doesn't seem to be working.

**Comment by Lin-Buo-Ren** [comment]
Getting this today...

**Comment by popey** [comment]
Still getting this. Would be really nice to get some eyeballs on it. It's terribly frustrating to be unable to add repos to my list because of this bug

**Comment by popey** [comment]
![hb](https://user-images.githubusercontent.com/1841272/55967321-0156be80-5c72-11e9-8305-5b21db93839d.gif)

**Comment by bartaz** [comment]
Sorry for the frustrating issue guys. We can't get to the bottom of this bug. It seems to only happen on production deployment in "some" circumstances and we simply couldn't find when and why it happens. Not talking about being able to debug it or anything.

As it seems to be related do memcached, I attempted to restart memcached on prod.
I was getting the "invalid handle" error before that today, but I'm able to sign in now.

@popey @Lin-Buo-Ren Could you try to sign in again and see if it still happens to you?

**Comment by popey** [comment]
I successfully logged in about 6 minutes ago. So that would tie in with the time you restarted memcached.

**Comment by Lin-Buo-Ren** [comment]
I can do the previous operation properly

**Comment by om26er** [comment]
The "technique" I try to workaround this bug is to go to login.ubuntu.com and SignOut. Sometimes that works, the other times doesn't. Though for the past two weeks, I have seen this issue quite often.

**Comment by Lin-Buo-Ren** [comment]
After I cleared the b.s.i site's (browser side) Indexed DB the problem is no longer reproduced, hope that helps.

**Comment by joedborg** [comment]
I'm seeing this again today.  Just FYI, I've tried with an existing browser profile where I'm logged in to both LP / Ubuntu One and GitHub.  I've also tried with a private browsing window and logging into everything from scratch.  Seeing it when I try and click "Sign In..." in the "Not registered" cell on the "Registered for release" column.

**Comment by joedborg** [comment]
![Screenshot from 2019-09-24 12-18-39](https://user-images.githubusercontent.com/1426404/65530243-8dc60800-dec5-11e9-9275-e8c7adcb3c1c.png)

**Comment by popey** [comment]
I saw it last week in Paris, and ended up having to sign in on my phone and doing the work there.

**Comment by om26er** [comment]
"me too", happened just yesterday when I was setting up a new project. Sometimes opening a totally new browser session helps (incognito mode) but other times it becomes a challenge.

This issue has been there long enough that its becoming embarrassing for the Snapcraft ecosystem as that could become the first big hurdle for anyone getting started with the build service.

**Comment by joedborg** [comment]
I've tried in Tor, behind proxies, on different machines and either seeing "Invalid association handle" or "Invalid signature" for the last week.  Sadly, this means that there's currently no way I can get my snap building via snapcraft io (which is a Canonical project).  Is there anyway I can get this done via the CLI or someone from the team do it manually?  I need the snap built cross platform.

**Comment by bartaz** [comment]
@joedborg Sorry about that. I restarted memcached service (which is usually helps with this issue) and I can sign in myself now. Could you give it another try to check if it helped for you as well?

**Comment by joedborg** [comment]
Thanks for trying @bartaz, sadly I'm still getting "Error:Invalid association handle".  That was in a private window.

**Comment by galgalesh** [comment]
I keep seeing this in Firefox. This is currently blocking me from publishing a snap. What can I do to work around this issue?

**Comment by galgalesh** [comment]
Also, @bartaz, this issue is happening consistently every time for me. Let me know if I can do anything to help debug this.

**Comment by galgalesh** [comment]
This issue is till happening for me on every try. I currently have two snaps which I can't publish to the store because of this issue.

**Comment by popey** [comment]
Most recently I have worked around this by using my phone to do the register dance.

**Comment by galgalesh** [comment]
Thanks @popey it **worked immediately on my phone**. I tried it a few more times and I get consistent behavior:

* It doesn't work on my laptop on any browser, even in private mode.
* It works on my phone on any browser, even in private mode.

Both my phone and laptop use the same WIFI network.

**Comment by popey** [comment]
Had it again today, and had to use my phone. I don't think it's clear how frustrating this bug is, even with the workaround. It's time consuming to switch to the phone because I have to:

  * Try and connect an application in the browser on my desktop
  * Realise it didn't work and now context switch to the phone
  * Open a private browsing window
  * Login to github (this requires typing in a long complex password and typing in a 2fa code)
  * Scroll down a barely readable page on my tiny phone display
  * Click the app in question, click register name
  * Sign into Launchpad with another long user and password (and 2fa)
  * Wait, go back and try to register the name

It's quite a time sink every time I have to use this workaround.

**Comment by solazio** [comment]
:pray: thanks everyone for being involved. This is now not applicable to the `Builds` tab on snapcraft.io
