### ISSUE TITLE
"Sign in" flow not working, stuck at empty page

### ISSUE THREAD

**Issue by nataliabidart** [canonical-web-and-design/build.snapcraft.io#629]
Hello,

I was setting up a repo for the first time, I logged in using my GH creds, I added a very small and simple repo. I the tried to register the name, and when I clicked on "Sign in" I was taken to prod SSO (good), I entered my SSO prod creds, my 2fa token, and after some seconds was redirected back to the BSI site, to my repo page, with the same legend about me needing to login to Ubuntu One and the "Sign in" green button enabled.

I assumed some glitch happened so I clicked on the "Sign in" button again, and given I was logged in in prod SSO already, what I see now is just an empty page that does not go anywhere. The URL shown in the browser is:

https://login.ubuntu.com/+openid?openid.mode=checkid_setup&openid.ns=http%3A%2F%2Fspecs.openid.net%2Fauth%2F2.0&openid.ns.sreg=http%3A%2F%2Fopenid.net%2Fextensions%2Fsreg%2F1.1&openid.sreg.required=nickname%2Cemail%2Cfullname&openid.ns.macaroon=http%3A%2F%2Fns.login.ubuntu.com%2F2016%2Fopenid-macaroon&openid.macaroon.caveat_id=%7B%22secret%22%3A%20%22qH4P%2FFQyGoxLFe6gr8pJkiSOrqFEPq9gNLjd1xuzZN68Tf%2FRu5G1IJnApDLpmEtc%2B1LF4ULz68CFaHVKqEA7LSRQYNZE111f6wimw4ROsNM94f1Z0c1dllMf2Qg%2BdILHiQqBe2PJP960ZVR0UQ4zo7Z%2BT2TsKYDNVoa3hxJ3VBasphM6z7oIaKeUT1RtCh9FhLQCCoUpM1TKbjZy0n0otWfIM09JOcRICETsmIsactSJZ7Rm5b6P2jWSFY8L%2BrtoTlSEF%2Br4kYtK%2BOj%2BF4kTkCvdRjl3%2BNai2UQKJ3G7FdGTQ4hgmNeDjDSJmZmwWmQVLpjTGZJ7EcW%2BNMCfhyWhlQ%3D%3D%22%2C%20%22version%22%3A%201%7D&openid.identity=http%3A%2F%2Fspecs.openid.net%2Fauth%2F2.0%2Fidentifier_select&openid.claimed_id=http%3A%2F%2Fspecs.openid.net%2Fauth%2F2.0%2Fidentifier_select&openid.assoc_handle=%7BHMAC-SHA256%7D%7B58ee40be%7D%7B9uM7KQ%3D%3D%7D&openid.return_to=https%3A%2F%2Fbuild.snapcraft.io%2Flogin%2Fverify%3Fstarting_url%3Dhttps%253A%252F%252Fbuild.snapcraft.io%252Fuser%252Fnataliabidart%26caveat_id%3D%257B%2522secret%2522%253A%2520%2522qH4P%252FFQyGoxLFe6gr8pJkiSOrqFEPq9gNLjd1xuzZN68Tf%252FRu5G1IJnApDLpmEtc%252B1LF4ULz68CFaHVKqEA7LSRQYNZE111f6wimw4ROsNM94f1Z0c1dllMf2Qg%252BdILHiQqBe2PJP960ZVR0UQ4zo7Z%252BT2TsKYDNVoa3hxJ3VBasphM6z7oIaKeUT1RtCh9FhLQCCoUpM1TKbjZy0n0otWfIM09JOcRICETsmIsactSJZ7Rm5b6P2jWSFY8L%252BrtoTlSEF%252Br4kYtK%252BOj%252BF4kTkCvdRjl3%252BNai2UQKJ3G7FdGTQ4hgmNeDjDSJmZmwWmQVLpjTGZJ7EcW%252BNMCfhyWhlQ%253D%253D%2522%252C%2520%2522version%2522%253A%25201%257D&openid.realm=https%3A%2F%2Fbuild.snapcraft.io

**Comment by solazio** [comment]
Not relevant for snapcraft.io, closing
