### ISSUE TITLE
PC may indicate only desktop computers in some languages

### ISSUE THREAD

**Issue by nataliabidart** [canonical-web-and-design/build.snapcraft.io#632]
This maybe is a silly bug report, but in Spanish, when you say "PC" you only mean the big computer thingy that you have in your desktop with external monitor, keyboard, mouse. In the common speech, PC does not include laptops or notebooks.
I would recommend replacing "your PC" with "your computer".

**Comment by solazio** [comment]
Not relevant for snapcraft.io, closing
