### ISSUE TITLE
Drop "we're working hard on making…" when form submitted

### ISSUE THREAD

**Issue by evandandrea** [canonical-web-and-design/build.snapcraft.io#634]
<img width="590" alt="screen shot 2017-04-13 at 10 34 26" src="https://cloud.githubusercontent.com/assets/1523179/24999298/e2baa570-2034-11e7-8cae-84debd7a25b4.png">

Steps to reproduce:

1. Fill out the private repos form
1. Hit submit

What happens:

- The message "We're working hard on making these repos buildable…" message persists.

What should happen:

- The message "We're working hard on making these repos buildable…" message is not shown.
- The message "Almost finished…" is the only message shown.

**Comment by solazio** [comment]
Not relevant for snapcraft.io, closing
