### ISSUE TITLE
Refactor (split up) RepositoryRow component

### ISSUE THREAD

**Issue by bartaz** [canonical-web-and-design/build.snapcraft.io#638]
RepositoryRow component now holds quite a lot of functionality.

Even with dropdowns moved to separate modules the main component code is quite big and holds a lot of functionality and logic that makes it harder to read and could make it error prone to add new functionality there.

Example: https://github.com/canonical-ols/build.snapcraft.io/pull/636#discussion_r111927086

**Comment by solazio** [comment]
Not relevant for snapcraft.io, closing
