### ISSUE TITLE
Refactor snap builds in launchpad state in the store

### ISSUE THREAD

**Issue by bartaz** [canonical-web-and-design/build.snapcraft.io#639]
Extracted from #465 to be tracked as separate task, because it involves several parts on it's own.

- [ ] move snapBuilds data to entities
- [ ] use arrays of ids to list builds for given snaps/repos
- [ ] normalize API responses with snap builds data
  - use CALL_API middleware if relevant
  - whitelist and camelCase properties returned by API

**Comment by solazio** [comment]
Not relevant for snapcraft.io, closing
