### ISSUE TITLE
Update snapcraft install instructions to use the candidate channel [1]

### ISSUE THREAD

**Issue by evandandrea** [canonical-web-and-design/build.snapcraft.io#642]
Snapcraft has been published to the candidate channel. Please update the installation instructions to match:

`snap install --candidate --classic snapcraft`

**Comment by nottrobin** [comment]
As in we will be asking users to install the beta version of Snapcraft? Why wouldn't we want to keep them on the stable version?

**Comment by nottrobin** [comment]
The instructions appear on build details pages:

![install](https://assets.ubuntu.com/v1/63a052df-install-instructions.png)

**Comment by matthewpaulthomas** [comment]
@nottrobin Because (I assume) there isn’t currently a stable version of the snapcraft snap (just a stable version of the .deb).

Anyway, [spec updated](https://docs.google.com/document/d/1koTwI3cRr2S2vj5zHKKbR7aWxLRfShDVq2gHQ29cDyU/edit#bookmark=id.fb6xz08fuya5).

**Comment by evandandrea** [comment]
Exactly that. We're waiting for the snapcraft team to publish a version to a higher channel than edge. Once they do that, we should switch our instructions over to it. Otherwise we may end up pointing developers at bleeding edge versions of snapcraft.

**Comment by evandandrea** [comment]
Snapcraft is now in the beta channel, so this is unblocked.

https://forum.snapcraft.io/t/call-for-testing-snapcraft/405

**Comment by evandandrea** [comment]
Now in the candidate channel.

**Comment by nottrobin** [comment]
build.snapcraft.io is being retired. I don't think this is an issue on snapcraft.io.
