### ISSUE TITLE
Ensure breadcrumbs styling is consistent with existing patterns

### ISSUE THREAD

**Issue by nottrobin** [canonical-web-and-design/build.snapcraft.io#653]
The style for the breadcrumbs on e.g. [a build details page](https://build.snapcraft.io/user/nottrobin/documentation-builder/33818) should either:

- follow the [vanilla breadcrumbs pattern](https://docs.vanillaframework.io/en/patterns/breadcrumbs), or
- use a pattern from an existing official theme, or
- formally define a new pattern

**Comment by matthewpaulthomas** [comment]
Reported [vanilla-framework issue #1034](https://github.com/vanilla-framework/vanilla-framework/issues/1034).

**Comment by matthewpaulthomas** [comment]
This was already wireframed in the spec, but [now made more explicit](https://docs.google.com/document/d/1koTwI3cRr2S2vj5zHKKbR7aWxLRfShDVq2gHQ29cDyU/edit#heading=h.ck0szfxlgnwh): “The hierarchy navigation (breadcrumbs) should follow [the Vanilla style](https://docs.vanillaframework.io/en/patterns/breadcrumbs) (with [vanilla-framework #1034](https://github.com/vanilla-framework/vanilla-framework/issues/1034#issuecomment-297052919) fixed).”

**Comment by solazio** [comment]
Not relevant for snapcraft.io, closing
