### ISSUE TITLE
Check all "removing a repo" functionality works as per the spec [1]

### ISSUE THREAD

**Issue by nottrobin** [canonical-web-and-design/build.snapcraft.io#664]
Ensure that all the states mentioned in the ["removing a repo" section of the spec](https://docs.google.com/document/d/1koTwI3cRr2S2vj5zHKKbR7aWxLRfShDVq2gHQ29cDyU/edit#heading=h.q8fitjuvz7vi) work as specified.

**Comment by solazio** [comment]
Not relevant for snapcraft.io
