### ISSUE TITLE
"My repos" page: Progressively load new rows [2]

### ISSUE THREAD

**Issue by nottrobin** [canonical-web-and-design/build.snapcraft.io#666]
When a new repo is added (from the "Add repos" list), currently there is a delay before the new row is added to the table, which may confuse the user.

To avoid this, the following solution was discussed in the workshop:

- Show the row immediately, filling in at least the repository name, leaving other columns blank
- Fill in the other columns when the data arrives from the server
- If the data takes more than 2 seconds to arrive, show placeholder text (e.g. "Scanning")

The exact text is still to be designed.

**Comment by solazio** [comment]
Not relevant for snapcraft.io
