### ISSUE TITLE
Linting snapcraft.yaml

### ISSUE THREAD

**Issue by nottrobin** [canonical-web-and-design/build.snapcraft.io#668]
Check the snapcraft.yaml is valid, and expose this in the "My repos" dashboard.

As a first pass, we should do the linting within the build.snapcraft.io app. But down the line we may be able to pass this responsibility to the snap store instead.

**Comment by nottrobin** [comment]
This might resolve #548 as well. @bartaz, @matthewpaulthomas or anyone who knows, please weigh in?

**Comment by matthewpaulthomas** [comment]
If they are implemented separately, after #548 you’d be able to expand an “Error” cell to see something like:
> The snapcraft.yaml can’t be used because it isn’t valid. Try using __kwalify__ or [yamllint.com](http://www.yamllint.com/) to debug it.
> ( Edit snapcraft.yaml… )

After #668, expanding an “Error” cell would instead show something like:
> The snapcraft.yaml can’t be used because it isn’t valid. ( Edit snapcraft.yaml… )
> `duplicated mapping key at line 4, column 13:`
>` ____name: test-1`
>`________________^`

It will be a while before I get to either of these, so I’ll leave it up to @bartaz to decide whether it’s worth designing+implementing them separately or together.

**Comment by matthewpaulthomas** [comment]
[Spec updated](https://docs.google.com/document/d/1koTwI3cRr2S2vj5zHKKbR7aWxLRfShDVq2gHQ29cDyU/edit#heading=h.j4z5b2pn5rsf).

**Comment by nottrobin** [comment]
Waiting for decisions from #909

**Comment by nottrobin** [comment]
Ah we already have https://github.com/canonical-websites/build.snapcraft.io/issues/548, so it's possible all we need for this is to do basic YAML validation?

**Comment by nottrobin** [comment]
Decisions from #909:

> @nottrobin:
> maybe all we need for #668 is YAML validation, which would be fairly simple.

> @evandandrea:
> I think that's reasonable, and a good first step. The reported cases of this have all been invalid yaml, not a missing part definition.
> Step two would be to validate against [the schema](https://github.com/snapcore/snapcraft/blob/master/schema/snapcraft.yaml). Step three would hand off that responsibility to snapcraft, where it could run deeper sanity tests.

**Comment by matthewpaulthomas** [comment]
From #943, this problem has been [discussed in the Snapcraft forum](https://forum.snapcraft.io/t/build-service-snapcraft-yaml-can-t-be-used-because-it-isn-t-valid/1958).

**Comment by dceejay** [comment]
Is there an external linter we can use to check that is same as the one that you are using ?
I tried yamllint.com and my file is valid there - but fails to build here... with no useful output I'm stuck.

**Comment by bartaz** [comment]
@dceejay We are using [js-yaml](https://www.npmjs.com/package/js-yaml) that has an online demo at http://nodeca.github.io/js-yaml/ where you can paste your `snapcraft.yaml`

**Comment by dceejay** [comment]
That works ! (better than yamllint.com :-) 
As a temp fix could a link to that be added to the current error as per #943

**Comment by solazio** [comment]
We check if the snapcraft.yaml file is valid when connecting to a GH repo on snapcraft.io
