### ISSUE TITLE
On build page, install instructions can be buried by long build log

### ISSUE THREAD

**Issue by matthewpaulthomas** [canonical-web-and-design/build.snapcraft.io#677]
From design review: A long log can push the instructions down. Could be fixed by making the log…
- collapsed by default
- below the instructions
- a link that opens a separate window/tab
- a scrolling frame

**Comment by bartaz** [comment]
It is a scrolling iframe ATM (300px height).

**Comment by solazio** [comment]
Not relevant for snapcraft.io
