### ISSUE TITLE
Webhook setup should be idempotent

### ISSUE THREAD

**Issue by evandandrea** [canonical-web-and-design/build.snapcraft.io#68]
Splitting this out of https://github.com/canonical-ols/build.snapcraft.io/issues/46. I'm seeing a 422 when inputting any valid repo.

/webhook:

>{"status":"error","payload":{"code":"github-already-created","message":"A webhook already exists on the given repository"}}

To which Colin replied, "The webhook case should be a separate issue because we're going to need to deal with that in a specialised way (webhook setup should be idempotent, basically)."

**Comment by bartaz** [comment]
I guess from a user point of view it's not much of an issue - it simply means that webhook is already in place.

Of course having error response hit the browser and being visible in the console or debug tools is not nice, so in theory we may process it on server side and send as success to the client.

**Comment by cjwatson** [comment]
This indeed isn't a major user-visible problem, particularly now that we redirect to `/:account/:repo/builds` if the snap already exists, which bypasses webhook creation.

However, the idempotency issue is that if we ever change the webhook config for whatever reason, then we should be able to update it via repository setup; so I'd argue that if the webhook already exists then we should update it with the current config.  https://developer.github.com/v3/repos/hooks/ suggests that this is possible although I haven't worked out the exact details.

We can then indeed reply with a 2xx response.

**Comment by solazio** [comment]
Not relevant for snapcraft.io, closing
