### ISSUE TITLE
Update icons in My Repos table

### ISSUE THREAD

**Issue by bartaz** [canonical-web-and-design/build.snapcraft.io#685]
We should update icons according to new visual design of My Repos table:
<img width="597" alt="screen shot 2017-04-25 at 13 22 36" src="https://cloud.githubusercontent.com/assets/83575/25383024/607b6b0a-29ba-11e7-8684-a9aa8e9c764a.png">

**Design needed:**

We need a list of all the icons we need in different statuses: configured, not configured, error, warning, etc

Also we need icons for different build statuses.

**Comment by magdalena-mirowicz** [comment]
@bartaz could you add estimate in brackets please? thanks

**Comment by kwm14** [comment]
## Updated design with new icon set

![01-my-repos-rows-updated](https://cloud.githubusercontent.com/assets/17748020/25710312/ccf7a0d4-30e3-11e7-8d52-53918f9a89ed.png)

## New icons
- @bartaz please find list of assets for icons in table

### Configured
**Scanning...**
No icon required - text only

**Not configured**
No icon required - text only

**Name mismatch**
https://assets.ubuntu.com/v1/e09a9810-warning.svg

**Error**
https://assets.ubuntu.com/v1/5594880d-error.svg

**Configured**
https://assets.ubuntu.com/v1/590f1b81-success-green-fill.svg

### Registered for publishing
**Checking...**
No icon required - text only

**Not registered...**
No icon required - text only

**Reassigned**
No icon required - text only

**Registered**
https://assets.ubuntu.com/v1/590f1b81-success-green-fill.svg

### Latest build
**Never built**
No icon required - text only

**Building soon**
No icon required - text only

**In progress**
https://assets.ubuntu.com/v1/8b7b3046-loading.png

**Failed to build**
https://assets.ubuntu.com/v1/5594880d-error.svg

**Built, won’t be published**
https://assets.ubuntu.com/v1/20cf5537-success-grey-outline.svg

**Built, publishing soon**
https://assets.ubuntu.com/v1/c3321c8a-queued.svg

**Built, failed to publish**
https://assets.ubuntu.com/v1/5594880d-error.svg

**Built and published**
https://assets.ubuntu.com/v1/590f1b81-success-green-fill.svg

**Connection error**
No icon required - text only

**Comment by solazio** [comment]
Not relevant for snapcraft.io, closing
