### ISSUE TITLE
Handle non-JSON responses from SCA better

### ISSUE THREAD

**Issue by sparkiegeek** [canonical-web-and-design/build.snapcraft.io#691]
Currently `auth-store.js` will call APIs on SCA, and universally expect JSON back. In the face of infrastructure problems or anything untoward happening, we might not get JSON back. These response handlers should cope with that gracefully and not just blow up.

**Comment by evandandrea** [comment]
See also #533

**Comment by solazio** [comment]
Not relevant for snapcraft.io, closing
