### ISSUE TITLE
“To test this build” text is inaccurate

### ISSUE THREAD

**Issue by matthewpaulthomas** [canonical-web-and-design/build.snapcraft.io#694]
[Split off from #641]

Currently on individual build pages, for published builds, we invite you to install that build for testing:

![“To test this build on your PC or cloud instance: … The installed snap will not be updated.”](https://cloud.githubusercontent.com/assets/1523179/25176665/de20109c-24f6-11e7-90a7-bcd35065f4bd.png)

Unfortunately, this is both inaccurate and incomplete:
<table>
<tr><th>What it claims/implies</th><th>What currently happens</th><th>What snapd developers are proposing</th></tr>
<tr><td>Publishers/collaborators can install any specific revision ever published</td><td>? <strong>(A)</strong></td><td>Publishers/collaborators can install any specific revision ever published, except that they can install a revision before their currently-installed one <em>only if they had previously installed it</em></td></tr>
<tr><td>Non-publishers + non-collaborators can also install any specific revision ever published</td><td>? <strong>(D)</strong></td><td>Non-publishers/collaborators can’t install past revisions at all</td></tr>
<tr><td>If you install a specific revision, it will not be updated automatically</td><td>If you install a specific revision, it will be updated within ~6 hours of a new revision being released</td><td>If you install a specific revision, it will be updated within ~6 hours of a new revision being released</td></tr>
<tr><td>—</td><td>Short of disconnecting from the Internet, there’s no way to stop the revision from being updated <strong>(J)</strong></td><td>If you want to delay your specific revision being replaced by a new revision, you should use a “postpone any refreshes by N hours” feature</td></tr>
<tr><td>—</td><td>To resume tracking latest without a new revision being released, uninstall+reinstall the snap <strong>(K)</strong></td><td>To prepone the postponed refresh, … ?</td></tr>
</table>

While we wait for the proposals to be implemented, we should fix the text to match current reality.

This requires answering these questions:

(A) Which revisions can publishers/collaborators currently install? Is there any limit on installing a revision if you have a newer revision currently installed?

(D) Which revisions can non-publishers + non-collaborators currently install? Is there any limit on installing a revision if you have a newer revision currently installed?

(J) Is this correct? Is there any kinder way of blocking updates to a particular snap?

(K) Is this correct? Is there any simpler way of updating to latest?

**Comment by evandandrea** [comment]
I think we should ask you to `snap login` (again) to work around current error messages being inaccurate:
```
$ sudo snap install --revision=17 bcc
error: cannot install "bcc": snap not found

$ sudo snap login
Email address: ev@ubuntu.com
Password of "ev@ubuntu.com": 
Two-factor code: 000000
Login successful

$ sudo snap install --revision=17 bcc
bcc 0.3.0-20170329-1737-26383f2 from 'ev' installed
```

**Comment by evandandrea** [comment]
>(A) Which revisions can publishers/collaborators currently install? Is there any limit on installing a revision if you have a newer revision currently installed?

Publishers/collaborators can install **any** revision, irrespective of the revision currently installed.

>(D) Which revisions can non-publishers + non-collaborators currently install? Is there any limit on installing a revision if you have a newer revision currently installed?

[Non-publishers/non-collaborators cannot install by revision.](https://forum.snapcraft.io/t/desired-refresh-behaviour-for-by-revision-installation/226/4?u=evan)

>(J) Is this correct? Is there any kinder way of blocking updates to a particular snap?

You can currently [schedule when refreshes occur every day](https://forum.snapcraft.io/t/refresh-schedule-via-core-config/434). In the future you will be able to [postpone refreshes, up to a certain number of hours.](https://forum.snapcraft.io/t/desired-refresh-behaviour-for-by-revision-installation/226/11?u=evan)

>(K) Is this correct? Is there any simpler way of updating to latest?

That's worth [raising to Gustavo here](https://forum.snapcraft.io/t/desired-refresh-behaviour-for-by-revision-installation/226/11?u=evan) as a desirable complement to the postpone refreshes feature.

**Comment by nottrobin** [comment]
build.snapcraft.io is being retired, and I think this is not an issue on snapcraft.io. Please open an issue on that repo if it is still a problem.
