### ISSUE TITLE
Name mismatch omits suggestions for how to fix the problem

### ISSUE THREAD

**Issue by matthewpaulthomas** [canonical-web-and-design/build.snapcraft.io#705]
1\. Add a repo.
2\. Register a name for the repo.
3\. If the repo doesn’t have one already, add a snapcraft.yaml that uses a different, unregistered, “name”.
4\. Click the “Doesn’t match”/“Name mismatch” (#703) cell.

What you see:
‘The snapcraft.yaml uses the snap name “my-snap-name”, but you’ve registered the name “mpt-test-ejejejejejejejej”.’

What you should see:
‘The snapcraft.yaml uses the snap name “my-snap-name”, but you’ve registered the name “mpt-test-ejejejejejejejej”. You can:
- Change snapcraft.yaml to use “mpt-test-ejejejejejejejej”
- Register the name “mpt-test-blabhalbhablhablh”’

**Comment by solazio** [comment]
Not relevant for snapcraft.io
