### ISSUE TITLE
Misleading language when deleting a project in build.sc.io

### ISSUE THREAD

**Issue by thomir** [canonical-web-and-design/build.snapcraft.io#710]
When clicking the 'trash can' icon for an already configured snap, build.snapcraft.io says:

`Removing this repo will delete all its builds and build logs. The name will remain registered.`

This makes it sound like the website will remove released revisions from the snap store, which it certainly shouldn't be doing.

**Comment by solazio** [comment]
This was fixed in the `Builds` tab on snapcraft.io
