### ISSUE TITLE
Hovering over build age underlines build status and not build age

### ISSUE THREAD

**Issue by matthewpaulthomas** [canonical-web-and-design/build.snapcraft.io#750]
1\. Have at least one repo that has completed building.
2\. Hover over the build age, for example “5 minutes ago”.

What happens:
- The build status is temporarily underlined.
- The text you’re actually hovering over is not underlined.

What should happen: either
- the build status should be underlined only when you hover over the build status; or
- the build status and build age should both be underlined when you hover over either.

**Comment by solazio** [comment]
Not relevant for snapcraft.io, closing
