### ISSUE TITLE
table row height doesn't match design

### ISSUE THREAD

**Issue by carlaberkers** [canonical-web-and-design/build.snapcraft.io#751]
Can we update the hight of table rows on the repos page to match the designs? 
According to the designs, based on MAAS tables, they should be 45px high, not 65px

**Comment by bartaz** [comment]
The table is implemented as in Jamie's design spec ([zip file](visual specification (unzip and open index.html)), which has 64px + 1px border.
Also in [presentation](https://docs.google.com/presentation/d/1tge2i4paDDVTPAXHLWJgMioNmkEOxr7giVvy7nPILRU/edit#slide=id.g214855b364_0_0) starting from slide 29.

If we want to have consistent styles with MAAS table, we need updated visual design that reflects that.

**Comment by solazio** [comment]
Not relevant for snapcraft.io, closing
