### ISSUE TITLE
Build status text colour and underline colour are inconsistent

### ISSUE THREAD

**Issue by matthewpaulthomas** [canonical-web-and-design/build.snapcraft.io#752]
1\. Have at least one repo that has built successfully.
2\. Hover over the build status.

What happens:
1\. The build status text is green.
2\. The text remains green but gets a blue underline.

What should happen: either
1\. The build status text should not be green, or
2\. on hover the text and underline are both green, or
3\. on hover the text and underline are both blue.

**Comment by kwm14** [comment]
## Visual reference
![table-row](https://cloud.githubusercontent.com/assets/17748020/25953884/936eb4dc-365c-11e7-894d-98858c423f0a.png)

- Link styling should follow what's seen under 'Name' in the current build.
- Vanilla reference **strong link** - https://docs.vanillaframework.io/en/patterns/links

**Comment by matthewpaulthomas** [comment]
@kwm14 Unfortunately, “Link styling should follow what’s seen under ‘Name’” is ambiguous because there is _also_ a problem with the link styling in that column, #763. Perhaps the solution to these two issues should be designed together.

**Comment by solazio** [comment]
Not relevant for snapcraft.io, closing
