### ISSUE TITLE
“Sign in…” changes to spinner + “Checking…”

### ISSUE THREAD

**Issue by matthewpaulthomas** [canonical-web-and-design/build.snapcraft.io#762]
Signed out of Ubuntu One:
1\. Add a repo.
2\. Click on “Not registered”.
3\. Click on “Sign in…”.

What happens: The text “Sign in…” changes to a spinner plus the word “Checking…”.

What should happen: The button label does not change. (It doesn’t need to, because a whole new page starts loading quickly enough.)

**Comment by solazio** [comment]
Not relevant for snapcraft.io, closing
