### ISSUE TITLE
In “My repos”, repo name styled identically whether or not it’s a link

### ISSUE THREAD

**Issue by matthewpaulthomas** [canonical-web-and-design/build.snapcraft.io#763]
1\. Have at least one repo that has built.
2\. Have at least one repo that has not built.
3\. In the “Repos to build and publish” table, compare the “Name” cell for each.

![build-snapcraft-name-cells](https://cloud.githubusercontent.com/assets/19801137/26053881/81f5bf1c-3962-11e7-9219-d72bbe13a5b3.png)

What you see:
- One is a link and one is not.
- Despite this, they are styled identically unless you hover over them.

What you should see: either
- they are both links, or
- they are styled differently.

**Comment by solazio** [comment]
Not relevant for snapcraft.io, closing
