### ISSUE TITLE
“Not configured” and “Not registered” don’t look clickable

### ISSUE THREAD

**Issue by matthewpaulthomas** [canonical-web-and-design/build.snapcraft.io#764]
In the “Repos to build and publish” table, cells that say “Not configured” or “Not registered” are clickable.

But except when you hover over them, they look almost identical to cells that are not clickable:
- white background
- black text
- no underline.

The only visual distinction is the chevron, which probably isn’t enough.

![snapcraft - not configured and not registered](https://cloud.githubusercontent.com/assets/19801137/26055662/b634f00c-3969-11e7-9b27-79d16fc8346c.png)

They should look more distinctive.

**Comment by solazio** [comment]
Not relevant for snapcraft.io, closing
