### ISSUE TITLE
Not obvious that “Not configured”/“Doesn’t match” panel links will open in new window/tab

### ISSUE THREAD

**Issue by matthewpaulthomas** [canonical-web-and-design/build.snapcraft.io#765]
1\. In the “Repos to build and publish” table, click any cell labelled “Not configured” or “Doesn’t match”.
2\. Look at the links in the revealed panel.

What you see: There is no clue that the links will open in a new window/tab.

What you should see: Visual reassurance that these links will open in a new window/tab, so you won’t lose your place in the app.

Vanilla includes [a pattern for “external” links](https://docs.vanillaframework.io/en/patterns/links#external-link), but this is not the same thing; it’s for links from different sites. Sometimes links on a different site should open in the same window/tab (for example, “Sign in”), and sometimes links on the same site should open in a different window/tab (for example, any help link).

**Comment by solazio** [comment]
Not relevant for snapcraft.io, closing
