### ISSUE TITLE
Erroneous snap name field doesn’t use standard error style

### ISSUE THREAD

**Issue by matthewpaulthomas** [canonical-web-and-design/build.snapcraft.io#766]
1\. For any repo, click “Not registered” or its existing registered name.
2\. Enter “-test”, or enter “test-” and choose “Register name”/“Change registered name”.

What happens: The field style does not change.

What should happen: The field acquires [the Vanilla standard style for erroneous fields](https://docs.vanillaframework.io/en/base/forms#validation-classes).

**Comment by matthewpaulthomas** [comment]
Spec updated:
- “[‘Register name’ should be disabled](https://docs.google.com/document/d/1koTwI3cRr2S2vj5zHKKbR7aWxLRfShDVq2gHQ29cDyU/edit#bookmark=id.9r0spyi9a925) whenever: … • the first character is a hyphen (with **the field also having the standard error style**, and the caption being replaced by an error message ‘Sorry, the name can’t start or end with a hyphen.’).”
- “[If registration fails](https://docs.google.com/document/d/1koTwI3cRr2S2vj5zHKKbR7aWxLRfShDVq2gHQ29cDyU/edit#bookmark=id.6xyaxxoqwng6), the spinner should revert to the button label, the field and button should become enabled again, **the field should acquire the standard error style**, and the caption should change to one of … The caption should return to its usual value, and **the field should lose the error style**, as soon as you make any change to the field value.”

**Comment by solazio** [comment]
Not relevant for snapcraft.io, closing
