### ISSUE TITLE
“Doesn’t match” touches the chevron

### ISSUE THREAD

**Issue by matthewpaulthomas** [canonical-web-and-design/build.snapcraft.io#767]
1\. Set up a repo such that its snapcraft.yaml name does not match its registered name.
2\. Look at the “Doesn’t match” cell.

What you see: “match” and the chevron are practically touching.

![snapcraft - doesn t match](https://cloud.githubusercontent.com/assets/19801137/26058162/889064a0-3974-11e7-81d6-d3dd71f06c5d.png)

What you should see: There is at least a word-space space between them.

**Comment by solazio** [comment]
Not relevant for snapcraft.io, closing
