### ISSUE TITLE
Timeouts of build.snapcraft.io in MS Edge

### ISSUE THREAD

**Issue by diddledan** [canonical-web-and-design/build.snapcraft.io#768]
Was working fine until around a deployment by cjwatson today (15/05). I had a page open in Edge (https://build.snapcraft.io/user/diddledan/corebird-snap) and noticed that the display changed without reloading the page to report some kind of error (I forget the actual wording). Manually altering the address bar URL to remove the subdirectories and load just https://build.snapcraft.io/ timed-out. Hitting refresh at that point also timed out. Hitting "back" to go back to https://build.snapcraft.io/user/diddledan/corebird-snap caused the site to start working fine again. Now refreshes and navigation all work correctly.

**Comment by evandandrea** [comment]
@popey are you able to reproduce this?

**Comment by nottrobin** [comment]
This should be considered high priority if it's reproducible by all users of Edge.

**Comment by diddledan** [comment]
I think it's important to make clear that it seemingly works fine again now and I can't get it to break again (yet).

**Comment by popey** [comment]
I didn't see it today when I was testing in Edge.

**Comment by bartaz** [comment]
From the report it seems that that the errors may be related to in-progress deployment.
It's likely that it's not Edge specific issue and possibly some requests could error during deployment in any browser.

**Comment by solazio** [comment]
Not relevant for snapcraft.io, closing
