### ISSUE TITLE
It's not clear that needing to be a repo admin is a GitHub restriction

### ISSUE THREAD

**Issue by evandandrea** [canonical-web-and-design/build.snapcraft.io#771]
<img width="454" alt="screen shot 2017-05-15 at 17 26 39" src="https://cloud.githubusercontent.com/assets/1523179/26067957/b4c5b6c8-3993-11e7-92ed-9972f474c677.png">

The "Any repos missing from this list?" message explains that you need admin permissions ("don't have admin permission"), but doesn't explain why this restriction is in place. We could explain that it [comes from GitHub](https://help.github.com/articles/about-webhooks/).

**Comment by evandandrea** [comment]
@mhall119 @matthewpaulthomas

**Comment by matthewpaulthomas** [comment]
How about:
“Don’t have **admin permission**? GitHub requires that a repo admin adds the repo. Once they do, it will show up in your repo list too.”

**Comment by evandandrea** [comment]
👍

**Comment by matthewpaulthomas** [comment]
[Spec updated](https://docs.google.com/document/d/1koTwI3cRr2S2vj5zHKKbR7aWxLRfShDVq2gHQ29cDyU/edit#bookmark=id.msdazl1vu8u7).

**Comment by solazio** [comment]
Not relevant for snapcraft.io, closing
