### ISSUE TITLE
When admin perms have been removed, removing a repo fails

### ISSUE THREAD

**Issue by evandandrea** [canonical-web-and-design/build.snapcraft.io#772]
<img width="1440" alt="screen shot 2017-05-15 at 16 58 24" src="https://cloud.githubusercontent.com/assets/1523179/26068068/2a228298-3994-11e7-83be-82f96c8181c7.png">

Not long ago admin of our GitHub organisation transferred from a few individuals, myself included, to a single account. Prior to this move I had set up CanonicalLtd/aws-snap on staging. In trying to remove it I get the following error:
```
{"status":"error","payload":{"code":"github-no-admin-permissions","message":"You do not have admin permissions for this GitHub repository"}}
```

We can't really remove it. We could hide the trash can icon in these cases and possibly display a message explaining why it cannot be removed.

**Comment by bartaz** [comment]
There are couple of related issues that need UX input: #998 #772 #1005 

The questions are:
- Should a user who is not an admin of the repo be able to remove the repo from the list? (they will not be able to add it back)
- We currently prevent users from removing repo with a registered name if they don't own the name, but it doesn't work well in case of name transfer. So maybe we should allow users to remove such repos, but warn them that they wont be able to add them back with the same registered name?

**Comment by solazio** [comment]
Not relevant for snapcraft.io, closing
