### ISSUE TITLE
No feedback on copy link

### ISSUE THREAD

**Issue by evandandrea** [canonical-web-and-design/build.snapcraft.io#777]
<img width="173" alt="screen shot 2017-05-16 at 17 01 39" src="https://cloud.githubusercontent.com/assets/1523179/26115936/5bd23d9a-3a59-11e7-8dea-c4a1a784275d.png">

Clicking the copy link provides no feedback. @matthewpaulthomas what do you think of adding something like this:

<img width="114" alt="screen shot 2017-05-16 at 17 03 03" src="https://cloud.githubusercontent.com/assets/1523179/26115997/8fa7222a-3a59-11e7-8020-e625ce30fe87.png">

**Comment by solazio** [comment]
Not relevant for snapcraft.io, closing
