### ISSUE TITLE
Badge Markdown is not visible

### ISSUE THREAD

**Issue by bartaz** [canonical-web-and-design/build.snapcraft.io#778]
Issue somehow related to #777

We only provide a copy button that automatically copies arbitrary Markdown to user's clipboard.

It would be better if we would show to users a piece of Markdown code that they are about to copy, so they would understand what they are copying and also would be able to use good ol' Ctrl+C to do that manually.

For example Travis and Coveralls open a popover with textarea showing badge code that can be copied:

<img width="1192" alt="screen shot 2017-05-17 at 08 48 48" src="https://cloud.githubusercontent.com/assets/83575/26141900/5a5ff120-3ade-11e7-981f-f6ac8e6bd4af.png">
<img width="1200" alt="screen shot 2017-05-17 at 08 50 18" src="https://cloud.githubusercontent.com/assets/83575/26141901/5a61f34e-3ade-11e7-8578-8fd45f0716e0.png">

**Comment by solazio** [comment]
Not relevant for snapcraft.io, closing
