### ISSUE TITLE
Clean-up (or remove) legacy form components

### ISSUE THREAD

**Issue by bartaz** [canonical-web-and-design/build.snapcraft.io#781]
In the prototype phase of the project we used some form components first introduced in my.ubuntu.com:
https://github.com/canonical-ols/build.snapcraft.io/tree/master/src/common/components/forms

The only one still in use in BSI is `Message` component (for some error and status messages), but it likely should be replaced, because it does not comply to the design spec or visual style.

**Comment by bartaz** [comment]
Now that we have more Vanilla components imported into project it makes even more sense to get rid of old form ones.

**Comment by solazio** [comment]
Not relevant for snapcraft.io, closing
