### ISSUE TITLE
Front page doesn’t acknowledge people who don’t have their code on GitHub

### ISSUE THREAD

**Issue by matthewpaulthomas** [canonical-web-and-design/build.snapcraft.io#794]
In videos, talks, and cards, we are promoting build.snapcraft.io as a way of getting your software to users of Linux OSes.

Even if we were not doing that, search engines and organic links would mean that many people arrive at build.snapcraft.io without going to snapcraft.io first.

This is fine, but build.snapcraft.io is entirely focused on people who have their code on GitHub. With the current contents of the front page, if your code is not on GitHub, you might reasonably conclude that you can’t create a snap at all.

Depending on the brand (#790), the top-level navigation might lessen this assumption, but we shouldn’t assume that people will heed the top-level navigation before closing the page.

Fixing this probably won’t require much change to the front page. Maybe a single line of text below the “Get started in minutes” button, something like “(Code not on GitHub? Learn about __other ways to use Snapcraft__.)”

**Comment by solazio** [comment]
Not relevant for snapcraft.io, closing
