### ISSUE TITLE
Other sharing options for install instructions

### ISSUE THREAD

**Issue by bartaz** [canonical-web-and-design/build.snapcraft.io#814]
In #655 we only implemented twitter sharing for now.

We should add other sharing options for install instructions.
Proposed in #655 were Facebook and Google+, also Reddit and HN were suggested.

For all of them we need a URL to share and possibly some additional text description.

**Comment by evandandrea** [comment]
1. Twitter (already supported)
  a. "Single-step install ${snap_name} on Linux: sudo snap install ${snap_name}"
1. https://news.ycombinator.com/submit
  a. title field: "Show HN: ${snap_summary_field}"
  b. url field: "${https://build.snapcraft.io/user/name/repo}"
1. https://lobste.rs/stories/new
  a. title field: "${snap_summary_field}"
  b. url field: "${https://build.snapcraft.io/user/name/repo}"
  c. tags: "snapcraft"

**Comment by solazio** [comment]
Not relevant for snapcraft.io, closing
