### ISSUE TITLE
'Name mismatch' doesn't fit in one line

### ISSUE THREAD

**Issue by bartaz** [canonical-web-and-design/build.snapcraft.io#815]
Text for name mismatch error was recently updated, but currently it doesn't fit into one line, making the row look misaligned.

<img width="1051" alt="screen shot 2017-05-30 at 10 11 42" src="https://cloud.githubusercontent.com/assets/83575/26574138/87a2c666-4520-11e7-8e13-2d0c0b335fba.png">

**Comment by solazio** [comment]
Not relevant for snapcraft.io, closing
