### ISSUE TITLE
The test instruction is wrong when using "devmode"

### ISSUE THREAD

**Issue by daker** [canonical-web-and-design/build.snapcraft.io#825]
I did build a snap with ```confinement: devmode```, but build.snapcraft.io shows the instruction to test it as follows :
```sudo snap install --edge $snapname --revision=3```

Using the above the instruction will result in an error : snap not found, it should show :
```sudo snap install --edge $snapname --revision=3 --devmode```

**Comment by bartaz** [comment]
Thanks for the report.

Yes, you are correct. We show don't take snap confinement into account when showing install instructions.

**Comment by daker** [comment]
@bartaz note that i am using an RPi, i was able to install other snaps before someone told me to use --devmode which means i was already logged

**Comment by bartaz** [comment]
@daker OK, thanks for update. That would likely mean these 2 issues are not exact duplicates.

**Comment by matthewpaulthomas** [comment]
[Spec updated](https://docs.google.com/document/d/1koTwI3cRr2S2vj5zHKKbR7aWxLRfShDVq2gHQ29cDyU/edit#heading=h.wnpsh1izlzz6).

**Comment by evandandrea** [comment]
Saw this surface again with [krop](https://github.com/gocarlos/krop) ([snapcraft.yaml](https://github.com/gocarlos/krop/blob/53c29d2ed19d8bbd5bfc2704e0373168638a2f22/snap/snapcraft.yaml))

<img width="428" alt="screen shot 2017-08-18 at 11 46 55" src="https://user-images.githubusercontent.com/1523179/29455923-18b2a832-840b-11e7-8d26-950ad4ed0725.png">
