### ISSUE TITLE
'Add repos' dialog should adapt height to viewport

### ISSUE THREAD

**Issue by bartaz** [canonical-web-and-design/build.snapcraft.io#829]
Follow up to #827 

We made 'Add repos' dialog scrollable in #827, but using a fixed height for it.

As per [spec](https://docs.google.com/document/d/1koTwI3cRr2S2vj5zHKKbR7aWxLRfShDVq2gHQ29cDyU/edit#heading=h.43owh6tjv12q), the dialog height should adapt to viewport height, show or hide first time heading, etc.
This functionality needs to be implemented here.

**Comment by bartaz** [comment]
@mpt With header, beta notification, user avatar and first time heading there is quite a lot of space taken already, leaving not much space for 'Add repos' dialog.

As far as I can see user avatar is removed from newer visual designs, but even without it it may be hard to fit everything on smaller screen.

How should we define the rules how to show 'Add repos' and other parts of the screen?
If screen is too small for first time heading should it be simply hidden (not displayed at all) or should user be able to scroll up to it?
Should we make space to make footer visible or should dialog just expands and keep footer off screen?

Screenshot below taken on screen with heigh of 1200px (which leaves over 1000px for whole page) and is likely more than usual laptop screen would have. Still, footer didn't fit the screen and significant amount of screen is taken by elements other than 'Add repos' dialog:

<img width="1099" alt="screen shot 2017-06-05 at 15 08 31" src="https://cloud.githubusercontent.com/assets/83575/26820330/65d389e2-4a9a-11e7-8d6f-0d2f36443ff5.png">

**Comment by bartaz** [comment]
@matthewpaulthomas Thanks for the update.

Vanilla has some breakpoints built in:
```
$breakpoint-x-small: 460px !default;
$breakpoint-small: 620px !default;
$breakpoint-medium: 768px !default;
$breakpoint-large: 1030px !default;
```
Where widths below `small` trigger mobile layout.

I guess we could start with these values as well to stay consistent.

From spec point of view it seems that everything needed for implementation is ready.

**Comment by solazio** [comment]
Not relevant for snapcraft.io, closing
