### ISSUE TITLE
Showing install instructions before published to edge

### ISSUE THREAD

**Issue by evandandrea** [canonical-web-and-design/build.snapcraft.io#835]
[From iliv](https://forum.snapcraft.io/t/incorrect-example-installation-command-on-build-snapcraft-io/945):

There appears to be a problem with snap package installation example. Once a package was built, the page showed me this:
```
To test this snap on your PC or cloud instance: 
sudo snap install --edge iliv-test-0
```

Running this command resulted in:
`error: cannot install "iliv-test-0": snap not found"`

However, when I clicked on the green text link "Built and published", it took me to another page where the same command example was a little different:
`sudo snap install --edge iliv-test-0 --revision=1`

This one worked.

**Comment by iliv** [comment]
Yeah, it did state very clearly that the package was successfully built but it was not available for installation for some time. Which is confusing.

**Comment by solazio** [comment]
Not relevant for snapcraft.io, closing
