### ISSUE TITLE
Can't access old build

### ISSUE THREAD

**Issue by bartaz** [canonical-web-and-design/build.snapcraft.io#836]
When a given snap has more then 10 builds there is now way to access older builds via BSI.

Currently we only fetch 10 latest builds from launchpad.

There are 2 places it affects:

1. Repo page - we only show 10 latest builds and user can't access older builds. There should be a paging or load more functionality to request older builds.

2. Build detail page - if the build user tries to access is not one of the 10 latest builds (for example they bookmarked the URL, remembered the build id or just kept the build page open in the browser) the build will not load. Only 10 latest builds are accessible via details page. It should be fixed so any previous build (as long as it's available on launchpad) should be accessible from build details page.

Example: https://build.snapcraft.io/user/paritytech/parity/43959

**Comment by bartaz** [comment]
This seems like 2 separate issues (even though the cause is similar).

1. Repo page should allow loading older builds - this one requires design.
2. Build detail page - should load any valid build. That it a bug that should be fixed.

**Comment by bartaz** [comment]
Related to #983

**Comment by solazio** [comment]
Not relevant for snapcraft.io, closing
