### ISSUE TITLE
My repos: Only show spinner after 2 seconds

### ISSUE THREAD

**Issue by bartaz** [canonical-web-and-design/build.snapcraft.io#846]
This is a follow up to #661

As per spec, the loading spinner should only appear if response didn't return in 2 seconds.

From the [comment](https://github.com/canonical-websites/build.snapcraft.io/issues/661#issuecomment-301746697):
> The same problem happens with the “Repos to build” table: the table headers do not appear immediately, but a spinner *does* appear immediately, making the page much jumpier than necessary. So I’ve just specced [the same for that table](https://docs.google.com/document/d/1koTwI3cRr2S2vj5zHKKbR7aWxLRfShDVq2gHQ29cDyU/edit#bookmark=id.5pmm5n1ik1zh).

**Comment by solazio** [comment]
Not relevant for snapcraft.io, closing
