### ISSUE TITLE
The search string is always treated as a single substring

### ISSUE THREAD

**Issue by bartaz** [canonical-web-and-design/build.snapcraft.io#883]
In add repos the search string is always treated as a single substring. For example, searching for “maas gui” does not return “maas-gui-vanilla-theme”, when it should.

Then search string contains spaces we should treat each parts as separate search terms.

**Comment by bartaz** [comment]
Should we combine separate search terms with "AND" or with "OR"?

Do does "maas gui" mean "maas AND gui" or "maas OR gui"? Should "maas gui" match repos with only "maas" or "gui" in names such as "vanilla-gui", "maas", etc?

**Comment by matthewpaulthomas** [comment]
Initially, I think a simple AND would be most useful and most consistent with common search UIs. We could later add an explicit “OR” operator if it’s ever needed (which I doubt).

**Comment by nottrobin** [comment]
build.snapcraft.io is being retired, so the only relevant search would now be on snapcraft.io. If this is still an issue there, please refile this issue over on the snapcraft.io repo. But I don't think it is.
