### ISSUE TITLE
Builds continue to be scheduled when no snapcraft.yaml exists

### ISSUE THREAD

**Issue by evandandrea** [canonical-web-and-design/build.snapcraft.io#885]
I noticed https://build.snapcraft.io/user/theshadowx/notes had a lot of failed builds. It looks like this landed before we had the check for a snapcraft.yaml (grepping through the git history doesn't show a snapcraft.yaml in the right place), so builds continue to be scheduled.

**Comment by solazio** [comment]
This no longer relevant for snapcraft.io
