### ISSUE TITLE
Revoking access without first signing out of build.snapcraft.io shows empty add page

### ISSUE THREAD

**Issue by evandandrea** [canonical-web-and-design/build.snapcraft.io#887]
<img width="1113" alt="screen shot 2017-07-18 at 13 34 31" src="https://user-images.githubusercontent.com/1523179/28315245-f494550a-6bbd-11e7-90f0-e690158a721c.png">

You're presented with the above select-repositories page if you revoke access to build.snapcraft.io from GitHub without first signing out of build.snapcraft.io. Can we check whether we're still connected/auth'ed and if not force a sign out of build.snapcraft.io?

**Comment by evandandrea** [comment]
Actually, that might be confusing. @matthewpaulthomas do you have any thoughts on what the correct behaviour would be?

**Comment by bartaz** [comment]
It may be a duplicate (or at least related to #422).

We don't have empty state for Add repos implemented yet, that may make this issue less confusing.
But still, even there we don't support not having access to repos. While users is signed in to BSI we assume we have access to repos (as they had to give it to us in first place).

I'm currently not sure if there is an easy way from GH API point of view to tell us we are in such situation. I would guess that we will get 404 or 401 in such cases. We could investigate more to see if we can detect such case and act on it.

**Comment by solazio** [comment]
Not relevant for snapcraft.io, closing
