### ISSUE TITLE
Detect classic snaps and give correct install instructions

### ISSUE THREAD

**Issue by evandandrea** [canonical-web-and-design/build.snapcraft.io#900]
![screen shot 2017-07-24 at 21 54 34](https://user-images.githubusercontent.com/1523179/28544359-be4146b4-70ba-11e7-85f5-48d8318127d3.png)

Classic snaps require installing with `--classic`. Heroku [has been updated](https://github.com/heroku/cli/blob/aa05cb0cc526bbcc5012a6525ff07fc22370328e/snap/snapcraft.yaml) to be a classic snap.

**Comment by bartaz** [comment]
Possibly related to #825 (devmode)

**Comment by matthewpaulthomas** [comment]
It may save time to fix [snapcraft.io#928](https://github.com/canonical-websites/snapcraft.io/issues/928) at the same time as this bug.

**Comment by anthonydillon** [comment]
As a user test. I tried to install go as a snap today. I copied the command and it errored, warning me I should use `-classic`. It would be better to give me the correct/working command with explanation of what classic is doing. Instead of giving me a command that will fail.

**Comment by nottrobin** [comment]
build.snapcraft.io is being retired, and I'm 99% sure this is not an issue on snapcraft.io.
