### ISSUE TITLE
Badge status depends on which arch finish last

### ISSUE THREAD

**Issue by didrocks** [canonical-web-and-design/build.snapcraft.io#902]
Context:
* the b.snapcraft.io status badge was added to the ubuntu-make repository yesterday.
* this triggered a build with a failure on amd64 probably due to a new snapcraft/distro issue.
-> amd64 and armhf were built as we can see https://build.snapcraft.io/user/ubuntu/ubuntu-make (build #59531 and #59532).
* the badge was "in failure", I assume amd64 finished after amrhf, but the duration reported seems to contradicts this theory.
* As I didn't know if that was random or reproducible (and the failure is clearly not related to changing `README.md`, I did a dummy commit to trigger a new build (issue #901 is opened on a no possibility to retrigger a build without a dummy commit).
* Same failure on amd64, but still pass on armhf.
-> However, this time, the badge is OK, I assume armhf finished after amd64 on this run (but again, nothing apart the duration to confirm this).

The status badge seems thus quite random and should be global per commit, all archs status merged, to convery if the current snap is available for everyone using it or not.

**Comment by evandandrea** [comment]
Fixing this is dependent on first implementing build sets. I'll update this issue once we have that work captured in snapcraft and Launchpad.

See also https://github.com/canonical-websites/build.snapcraft.io/issues/905.

**Comment by solazio** [comment]
Not relevant for snapcraft.io, closing
