### ISSUE TITLE
"Already registered" when pending reserved name claim

### ISSUE THREAD

**Issue by evandandrea** [canonical-web-and-design/build.snapcraft.io#903]
<img width="1043" alt="screen shot 2017-07-25 at 12 34 28" src="https://user-images.githubusercontent.com/1523179/28570366-c9fd9482-7135-11e7-89aa-b95075695f6b.png">

I filed a request for the reserved name "paraview." It's still pending. When I try to register the name in build.snapcraft.io it says, "Name already registered" which isn't quite true. No one owns the name yet. The error is:
>https://dashboard.snapcraft.io/dev/api/register-name/
>{"status": 409, "code": "already_claimed", "title": "Name already registered.", "detail": "You already registered a claim for 'paraview'.", "error_list": [{"message": "You already registered a claim for 'paraview'.", "code": "already_claimed"}], "type": "devportal:v1:name-already-registered"}

**Comment by solazio** [comment]
Not relevant for snapcraft.io, closing
