### ISSUE TITLE
Create new vanilla forms component

### ISSUE THREAD

**Issue by richmccartney** [canonical-web-and-design/build.snapcraft.io#911]
## Summary

- Include the new dashboard theme form styles into BSI.
- SCSS to be found here https://github.com/vanilla-framework/vanilla-dashboard-theme/blob/develop/scss/_patterns_forms.scss

**Comment by bartaz** [comment]
PR #932 was closed unmerged because work there was not completed.

When form components will be planned to be added to BSI we can use work from this PR (branch https://github.com/canonical-websites/build.snapcraft.io/tree/911-forms-component) as a starting point.

**Comment by nottrobin** [comment]
I'm sure vanilla has moved on a lot since here, and now build.snapcraft.io is being retired. Closing.
