### ISSUE TITLE
Need to refresh page after going off to file a name claim

### ISSUE THREAD

**Issue by evandandrea** [canonical-web-and-design/build.snapcraft.io#914]
<img width="1039" alt="screen shot 2017-08-04 at 10 01 32" src="https://user-images.githubusercontent.com/1523179/28961956-07652d6c-78fc-11e7-9a25-9693f9c34bb1.png">

When you go off to file a reserved name claim and come back (after it's been assigned to you), there's no way to try registering the name again without first refreshing the page. Hitting cancel makes no difference.

**Comment by nottrobin** [comment]
We changed the priority because it is a rare circumstance indeed where someone will have been granted a snap name and returned to the page all in the same session. In that case it seems reasonable to expect them to reload the page.

**Comment by solazio** [comment]
Not relevant for snapcraft.io
