### ISSUE TITLE
Allow downloading gradle binary

### ISSUE THREAD

**Issue by koppor** [canonical-web-and-design/build.snapcraft.io#918]
## Summary

gradle is a a Java build tool. It offers a [wrapper](https://docs.gradle.org/4.0/userguide/gradle_wrapper.html), which downloads the build tool by itself. This is possible on Travis, but not on build.snapcraft.io:

```
Downloading https://services.gradle.org/distributions/gradle-4.0.2-bin.zip

Exception in thread "main" java.io.IOException: Unable to tunnel through proxy. Proxy returns "HTTP/1.1 407 Proxy Authentication Required"
```

Source: https://build.snapcraft.io/user/JabRef/jabref/67152

## Process

1. Create a snap requiring gradlew to build. Example: https://github.com/snapcore/snapcraft/tree/master/demos/gradle
2. Let it build on build.snapcraft.io

## Current and expected result

Expected: Download https://services.gradle.org/distributions/gradle-4.0.2-bin.zip succeeds

Current result: Download does not succeed. Download rejected with 407.

## Screenshot

![grafik](https://user-images.githubusercontent.com/1366654/29224460-bf4fc80a-7eca-11e7-8913-13e289c49d14.png)

**Comment by sparkiegeek** [comment]
I've proposed https://github.com/snapcore/snapcraft/pull/1490 which should fix this by having the gradle plugin pass on the username and password from $http_proxy and $https_proxy down to the build process

**Comment by solazio** [comment]
Not relevant for snapcraft.io, closing
