### ISSUE TITLE
Last step of first time heading re-appears when it shouldn't

### ISSUE THREAD

**Issue by bartaz** [canonical-web-and-design/build.snapcraft.io#920]
## Summary

Last step of 'first time heading' that says "Your first build is on the way" re-appears again in some cases.

## Process

1. Have a snap already build
2. Add another new repo, register name

First time heading should not appear again, but it does.

This is not a first repo that is built, so it shouldn't appear.
Also it seems that it appears even if repo is not configured, so build is not "on the way", because snapcraft.yaml is not in place yet.

This 2 cases may or may not be related.

## Screenshot

<img width="1072" alt="screen shot 2017-08-14 at 13 29 48" src="https://user-images.githubusercontent.com/83575/29270053-1c306490-80f5-11e7-9488-17790cba17ea.png">

**Comment by solazio** [comment]
Not relevant for snapcraft.io, closing
