### ISSUE TITLE
Release error looks like a notification, but isn’t

### ISSUE THREAD

**Issue by matthewpaulthomas** [canonical-web-and-design/build.snapcraft.io#935]
As of #930, when there is an error releasing a snap that was built by build.snapcraft.io, this is presented on the build page as a Vanilla-style error notification:

![](https://user-images.githubusercontent.com/83575/29608143-a1786972-87f3-11e7-8a68-8f626fe372d4.png)

Unfortunately, this does not fit [the pattern of a Vanilla-style error notification](https://docs.vanillaframework.io/en/patterns/notification) in three ways:
- It is not “global information”, but information specific to that build.
- It is always vital information about that build, so — unlike a notification — it will never disappear, even weeks or months later.
- It is not necessarily “information that is critical [where] the user should take action”, since it is moderately likely that the error will be fixed without user intervention (by someone else’s commit, by improved connectivity during the build process, by a dependency bugfix, etc).

If a failed release should be shown as an error notification, then for consistency, the log for a failed build should also be shown as an error notification. But that would be mistaken for the same three reasons.

The visual style of release errors should be the same as, or very similar to, the build log.

**Comment by solazio** [comment]
Not relevant for snapcraft.io, closing
