### ISSUE TITLE
Remove built CSS from the project

### ISSUE THREAD

**Issue by nottrobin** [canonical-web-and-design/build.snapcraft.io#941]
In both local development and for release, CSS should be built directly from vanilla-framework as needed.

**Comment by bartaz** [comment]
Jenkins job that builds BSI for deploy fails on installing node-sass, so would not build SCSS properly until we fix it:

```
12:54:19 O: > node-sass@4.5.3 install /workspace/build-snapcraft-io/build-snapcraft-io-build-charm/work/node_modules/node-sass
12:54:19 O: > node scripts/install.js
12:54:19 O: 
12:54:21 O: Downloading binary from https://github.com/sass/node-sass/releases/download/v4.5.3/linux-x64-48_binding.node
12:54:21 E: Cannot download "https://github.com/sass/node-sass/releases/download/v4.5.3/linux-x64-48_binding.node": 
12:54:21 E: 
12:54:21 E: tunneling socket could not be established, statusCode=403
12:54:21 E: 
12:54:21 E: Hint: If github.com is not accessible in your location
12:54:21 E:       try setting a proxy via HTTP_PROXY, e.g. 
12:54:21 E: 
12:54:21 E:       export HTTP_PROXY=http://example.com:1234
12:54:21 E: 
12:54:21 E: or configure npm proxy via
12:54:21 E: 
12:54:21 E:       npm config set proxy http://example.com:8080
```

**Comment by nottrobin** [comment]
Ah yes. That is about firewall restrictions.

Initially we should try adding `export HTTP_PROXY=http://squid.internal:3128` at the top of the job. If that doesn't fix it then we need to request access to NPM registry through that proxy server.

**Comment by nottrobin** [comment]
Out of curiosity, how do the other NPM dependencies find their way into the build?

**Comment by bartaz** [comment]
@nottrobin I suppose regular modules (JS only) are just downloaded from npm. This native module is downloading some binary from github as far as I understand.

**Comment by cjwatson** [comment]
Can we point it to something more local instead (maybe a dependencies branch of some kind)?  https://github.com/sass/node-sass/blob/master/lib/extensions.js#L208 might help.  https://github.com/sass/node-sass/blob/master/scripts/install.js doesn't even check the hash of what it's downloaded, so it's really not great to have it going out to the internet.

**Comment by nottrobin** [comment]
@cjwatson what is it that grabs the dependencies at present? Even if we grab dependencies elsewhere in the flow and push them to a dependency branch, I would be surprised if anyone is checking hashes in such a process. When we were forced to do that in the past, we certainly didn't check hashes. Let alone checking the actual contents of each imported module.

If we rely on NPM dependencies, I don't feasibly see any way around, or any problem with, ultimately trusting the NPM registry to deliver what it says it will. And while it might be nice to read the code of each and every module we import, this is simply not feasible.

Specifically for the node-sass binary, the problem with pushing it to and then retrieving it from a dependency branch is that it will fail to run in a different environment than the one it was built on.

Personally I would far rather get as close to pulling dependencies directly as we possibly can.

**Comment by cjwatson** [comment]
It's true that our installation process from the NPM registry doesn't currently check hashes either, but that will be fixed once we start using yarn or similar (yarn automatically stores hashes in its `yarn.lock`).

This is not about the NPM registry, though.

node-sass is presumably not needed at runtime, but only in development and when building artifacts for release, so I'm not sure the concerns about running in different environments are necessarily vital.  I agree that we want to try to keep the development process as smooth as possible, but there are reasons to apply at least a little bit of due diligence when downloading binaries from the internet too.

**Comment by nottrobin** [comment]
> It's true that our installation process from the NPM registry doesn't currently check hashes either, but that will be fixed once we start using yarn or similar (yarn automatically stores hashes in its yarn.lock).

I am all for using Yarn. You absolutely have my blessing to switch over to using that instead, and then request access to registry.yarnpkg.com instead of registry.npmjs.org. Although, I wouldn't be surprised if NPM 5 now offers the same functionality, as the main point of that version was to try to achieve feature parity with Yarn.

> node-sass is presumably not needed at runtime, but only in development and when building artifacts for release

This is true. Which is why it's important for the Jenkins job that does the building of artifacts to have access to what it needs to be able to do that. I'm not asking for access to any registries from the production environment. But to require a step to build and push dependencies for our build step to work is one too many levels of inception.

> there are reasons to apply at least a little bit of due diligence when downloading binaries from the internet too.

That's true. The only place this due diligence can feasibly be applied is in selecting which packages we depend on, and then when deliberately updating those packages. These are human decisions taken by the developer and the person who review their code.

Ultimately, however, we have to trust our package repositories. If we don't want to trust the package registries, I think it might also be possible to create our own mirror of those registries and configure the packaging tools in certain environments to use those mirrors instead. That would also work fine, as long as it doesn't add any extra complexity to the deployment process beyond `npm install` or `yarn install`.

**Comment by cjwatson** [comment]
You keep talking about trusting the package registries, and I'd like to clarify once again that I'm not talking about the registries themselves, but about the step in one of these packages to go off and fetch a binary from GitHub.

One problem with making a firewall/proxy configuration change here is that the only way we could do this would be to change it for the whole Jenkins instance it resides on, which affects much more than just this job.  Using a dependencies branch or some other strategy along those lines for the node-sass bindings binary (once again, I'm not asking for a change to how NPM packages in general are handled) would allow us to be more selective here.

**Comment by nottrobin** [comment]
> but about the step in one of these packages to go off and fetch a binary from GitHub.

Okay! Sorry yes I didn't realise that was your point.

Although thinking about it, is trusting this package to pull resources from its own GitHub releases page significantly different from trusting the package itself as it might be pushed to the NPM registry? Presumably a specific version of that NPM package is always going to pull a specific file from the same location on GitHub. Which, as long as we trust GitHub to function as expected (which we kinda do all the time) is actually basically the same as trusting the package that the developer may have pushed to NPM.

Anyway, if this is a serious concern, I would have thought the best way around it would be to install node-sass directly on the Jenkins worker - but that would mean we could be less certain that our Sass code works in development in the same way that it does when it's built for release.

**Comment by cjwatson** [comment]
The GitHub releases page is one thing, but I suspect it's going to be quite tricky to open up just GitHub releases and not the rest of GitHub (the GitHub URLs in question are immutable as long as we trust the project not to delete its tags, but most GitHub URLs are very much mutable); and like I say, I think we want to keep the restriction for other jobs running on the same Jenkins instance, of which there are many.

**Comment by nottrobin** [comment]
> I think we want to keep the restriction for other jobs running on the same Jenkins instance, of which there are many.

Okay. This process is on your Jenkaas installation for the time being, and we don't have time to move and take ownership of the deployment process right now (which is what would probably be required to move it to our Jenkaas), so I agree we need to work within the restrictions you feel comfortable with for the OLS Jenkaas.

Would you mind outlining specifically what a solution to providing the node-sass to this build job could look like?

In the case of the Webteam Jenkaas installation, we are simply going to get access to github.com along with all the package registries, which IS are happy to provide us with. Which is a good thing as we use node-sass in pretty much every project we have. So thankfully we won't need to worry about this complexity for our other projects.

**Comment by nottrobin** [comment]
It looks like NPM5 checks hashes, presumably in much the same way as Yarn:

https://docs.npmjs.com/files/package-lock.json#integrity

Does that address your concerns? Or do we still need to somehow do further checks on the binary?

**Comment by cjwatson** [comment]
I'd grab the relevant binding files from GitHub, stash them somewhere more local that's under our control (dependencies branch, committed to BSI itself, assets server, or whatever; I have no very strong feelings as long as it's gated by us), and set `SASS_BINARY_SITE` or `SASS_BINARY_PATH` as appropriate in the `git-build` rule in `Makefile` (which is called by Jenkins) to point to whatever the chosen local location is.

Unless I'm much mistaken, neither NPM5 nor Yarn helps with this; I believe that the hash checks they perform are only for files downloaded from the registry, not other miscellaneous bits and pieces that are downloaded by individual packages' install scripts.

**Comment by nottrobin** [comment]
@cjwatson would it be possible to simply install node-sass globally in the Jenkins workers? Then we can simply set SASS_BINARY_PATH to the system location for this build job.

**Comment by cjwatson** [comment]
Not sure how that would work.  Firstly, it doesn't appear to be packaged as a .deb; secondly, the slave containers are built dynamically with the same firewall restrictions, so any attempt to install from non-.deb sources would run into basically the same kinds of problems.

My feeling is that system installation would be more frustrating for you in the long run anyway; it would be more opaque and harder to upgrade.

**Comment by solazio** [comment]
Not relevant for snapcraft.io, closing
