### ISSUE TITLE
No links to documentation or developer support

### ISSUE THREAD

**Issue by evandandrea** [canonical-web-and-design/build.snapcraft.io#948]
We don't currently link to https://snapcraft.io/docs or https://forum.snapcraft.io. It's likely that the snapcraft.yaml template we generate won't be sufficient to get the developer to a working snap. They'll need to consult the documentation to know how to build a snap for the language of their project.

**Comment by matthewpaulthomas** [comment]
Making the headers consistent is a goal in itself. But when people have a snapcraft.yaml error, I think it’s much more likely that they’ll be looking at [the error message](https://docs.google.com/document/d/1koTwI3cRr2S2vj5zHKKbR7aWxLRfShDVq2gHQ29cDyU/edit#heading=h.j4z5b2pn5rsf) than at the header of the site. So regardless of the header, we should link to [the snapcraft.yaml syntax reference](https://snapcraft.io/docs/build-snaps/syntax) below the error message.

**Comment by solazio** [comment]
Not relevant for snapcraft.io, closing
