### ISSUE TITLE
No link from BSI repo page to GitHub repo page

### ISSUE THREAD

**Issue by matthewpaulthomas** [canonical-web-and-design/build.snapcraft.io#953]
There is currently no easy way to get from a BSI repo page to the equivalent GitHub repo page.

@evandandrea suggested adding a GitHub logo next to the repo name, like Travis does:

![image](https://user-images.githubusercontent.com/19801137/30313202-71d86036-9794-11e7-8e6d-bbe6e2f42c98.png)

**Comment by solazio** [comment]
Not relevant for snapcraft.io, closing
