### ISSUE TITLE
Delete button is inaccessible

### ISSUE THREAD

**Issue by matthewpaulthomas** [canonical-web-and-design/build.snapcraft.io#957]
1. With a screenreader, go to your “My repos” page.
2. Try to delete any of your repos.

What happens: As far as I can tell, you can’t. Worse, it looks deliberate.

The code for the delete button:
`<a class="table__dataLink___25WPl table__data___2JiSp table__cell___1R9BL table__expandable___3jQDN table__centered___3guOZ" href="#" style="width: 6%;"><i aria-hidden="true" class="icons__p-icon--delete___kCWtp undefined"></i></a>
`

Two things make it inaccessible:
- There‘s no fallback text if you can’t see the image for whatever reason.
- Even if there was fallback text, `aria-hidden="true"` would explicitly instruct screenreaders to omit it.

**Comment by solazio** [comment]
Not relevant for snapcraft.io, closing
