### ISSUE TITLE
Seems to break with leading dash in repository name

### ISSUE THREAD

**Issue by lool** [canonical-web-and-design/build.snapcraft.io#963]
Hi,

I'm reporting this on behalf of @davidahoward who tried setting up a build on build.snapcraft.io. This never completes, it spins forever when hitting "add repo". It might be due to the leading - in the repo name.

The repo is:
[https://github.com/davidahoward/-chuck-norris-webserver](https://github.com/davidahoward/-chuck-norris-webserver)

And here's a screenshot of the console when that happens:
![console-error](https://user-images.githubusercontent.com/22331/31037927-894fa2fa-a528-11e7-8547-5ae5f674222b.png)

Best,
`- Loïc Minier

**Comment by bartaz** [comment]
@lool Thanks for the report. We will look into this issue.

Can you give us a URL of the repo that causes the problem, so we could fork it and test?

**Comment by lool** [comment]
@bartaz I did give the URL in my initial report?!

**Comment by bartaz** [comment]
@lool @davidahoward Thanks, forked it already (https://github.com/bartaz/-chuck-norris-webserver) and will debug it from there.

**Comment by bartaz** [comment]
Confirmed. Adding repo with leading dash fails.

**Comment by solazio** [comment]
`-` leading names are not allowed on snaocraft.io, closing
