### ISSUE TITLE
Not clear what contact developers can expect

### ISSUE THREAD

**Issue by popey** [canonical-web-and-design/build.snapcraft.io#982]
When a developer signs up with the *beta* build service we should set communication expectations accordingly. As the site is in beta and developers may start to rely on the service, when it goes wrong, we will likely want to let those developers know. We should make it clear during the sign up process that we're likely to be contacting them with updates regarding the service, via email.

**Comment by evandandrea** [comment]
I've asked Alan to file this. It's worth exploring we can more visibly articulate that we may contact users of the service to assist or tell them about new features. GDPR may bring this requirement anyway.

See also https://github.com/canonical-websites/build.snapcraft.io/issues/731.

**Comment by solazio** [comment]
Not relevant for snapcraft.io, closing
