### ISSUE TITLE
Logged out vs logged in view differs oddly.

### ISSUE THREAD

**Issue by popey** [canonical-web-and-design/build.snapcraft.io#993]
## Summary

When logged out of build.snapcraft.io i see a summary of builds at this url:- 

https://build.snapcraft.io/user/Justinzobel/gmpc-snap

Thus:-

![image](https://user-images.githubusercontent.com/1841272/32304961-95f7483a-bf6a-11e7-8026-46054ad20661.png)

However, when I login, i see this:-

![image](https://user-images.githubusercontent.com/1841272/32304978-a8858c96-bf6a-11e7-8d00-839ceb85c52d.png)

## Process

In an incognito window visit the url above
In a logged in window, visit the same url

## Current and expected result

I was actually expecting to see _more_ when logged in, not less.

**Comment by bartaz** [comment]
@popey Can you still reproduce it?

When repo is not your own both views (signed in or not) should be more or less the same.

I can access the page you mentioned both when logged in or not:

<img width="1061" alt="screen shot 2017-11-02 at 08 52 23" src="https://user-images.githubusercontent.com/83575/32315160-5947d4ea-bfab-11e7-97e2-68bf46a1c90c.png">

**Comment by evandandrea** [comment]
Did you leave the page open? I’ve noticed this state when I leave a tab and the session expires.

**Comment by popey** [comment]
Huh, i can't reproduce it now. That's annoying.

**Comment by bartaz** [comment]
I guess it needs investigating. Especially in terms on what happens when users session times out.

**Comment by solazio** [comment]
Not relevant for snapcraft.io, closing
